OBJ        = vfkreader.obj vfkreadersqlite.obj \
	vfkdatablock.obj vfkdatablocksqlite.obj \
	vfkpropertydefn.obj \
	vfkfeature.obj vfkfeaturesqlite.obj \
	vfkproperty.obj

EXTRAFLAGS = -I.. -I..\.. $(SQLITE_EXTRAFLAGS)

GDAL_ROOT  = ..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

!IFDEF SQLITE_INC
SQLITE_EXTRAFLAGS = $(SQLITE_INC) -DHAVE_SQLITE
!ENDIF

default: $(OBJ)

clean:
	-del *.obj *.pdb
