GDAL_ROOT	=	..\..\..
EXTRAFLAGS=-DUSE_IN_GDAL $(SOFTWARNFLAGS)
!INCLUDE $(GDAL_ROOT)\nmake.opt


OBJ	=	endian.obj swapio.obj vs2.obj vsdef.obj rextend.obj\
vsvers.obj legend.obj strpad.obj strconst.obj vsis.obj ruseas.obj rmalloc.obj create2.obj \
_getcell.obj _getrow.obj _gsomece.obj _putcell.obj _rputrow.obj\
attravai.obj attrsize.obj csfglob.obj csfsup.obj delattr.obj\
filename.obj gattrblk.obj gattridx.obj gcellrep.obj \
 cellsize.obj gdattype.obj getattr.obj getx0.obj\
gety0.obj ggisfid.obj gmaxval.obj gminval.obj gnrcols.obj gnrrows.obj\
gproj.obj gputproj.obj gvalscal.obj gvartype.obj gversion.obj ismv.obj\
kernlcsf.obj mclose.obj mopen.obj mperror.obj \
pgisfid.obj pmaxval.obj pminval.obj putallmv.obj putattr.obj\
putsomec.obj putx0.obj puty0.obj pvalscal.obj rattrblk.obj rcomp.obj\
rcoords.obj rdup2.obj reseterr.obj \
rrowcol.obj setmv.obj setvtmv.obj moreattr.obj\
wattrblk.obj setangle.obj angle.obj dumconv.obj trackmm.obj

GDAL_ROOT	=	..\..\..


default:	$(OBJ)
	xcopy /D  /Y *.obj ..\..\o

clean:
	-del *.obj

