GDAL_ROOT = ..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

OBJ	= jpeglsdataset.obj

EXTRAFLAGS = -I.. -I..\.. $(CHARLS_INC) $(CHARLS_FLAGS)

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o
	cd ..
	
clean:
	-del *.obj
	cd ..
