
OBJ	=	ogrgftdriver.obj ogrgftdatasource.obj ogrgftlayer.obj ogrgfttablelayer.obj ogrgftresultlayer.obj
EXTRAFLAGS =	-I.. -I..\..

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



