/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.27
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gdal.osr;

public class SWIGTYPE_p_double {
  private long swigCPtr;

  protected SWIGTYPE_p_double(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_double() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_double obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

