OBJ	=	gdalconst_wrap.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..

clean:
	-del *.obj
	-del *.cs
	-del *.c
    -del *.csproj
    -del *.json
    -del *.dll
    -del *.pdb
    -rd /q /s obj

