#include "cpl_config.h"

/* Set the native cpu bit order */
#define HOST_FILLORDER FILLORDER_LSB2MSB

#define STRIPCHOP_DEFAULT TIFF_STRIPCHOP
#define DEFAULT_EXTRASAMPLE_AS_ALPHA 1
#define CHECK_JPEG_YCBCR_SUBSAMPLING 1
#define HAVE_IEEEFP 1

#define STRIPCHOP_DEFAULT TIFF_STRIPCHOP
#define JPEG_SUPPORT 1 
#define PIXARLOG_SUPPORT 1
#define ZIP_SUPPORT 1
#define LOGLUV_SUPPORT 1
#define NEXT_SUPPORT 1
#define THUNDER_SUPPORT 1
#define LZW_SUPPORT 1
#define PACKBITS_SUPPORT 1
#define CCITT_SUPPORT 1
