
OBJ	=	ogropenfilegdbdriver.obj \
		ogropenfilegdbdatasource.obj ogropenfilegdbdatasource_write.obj \
		ogropenfilegdblayer.obj ogropenfilegdblayer_write.obj \
		filegdbtable.obj filegdbtable_write.obj filegdbindex.obj filegdbindex_write.obj \
		filegdbtable_write_fields.obj filegdbtable_freelist.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS =	-I.. -I..\.. -I..\mem

default:	$(OBJ)

clean:
	-del *.obj *.pdb
