OBJ	=	osr_wrap.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt
!INCLUDE ..\java.opt

default:	$(OBJ)
	copy *.obj ..

clean:
	-del *.obj
	-del *.cs
	-del *.cpp

.cpp.obj:	
	$(CC) $(CFLAGS) $(JAVA_INCLUDE) /c $*.cpp
