
OBJ     =       shape2ogr.obj shpopen.obj dbfopen.obj ogrshapedriver.obj \
		ogrshapedatasource.obj ogrshapelayer.obj 
EXTRAFLAGS =	-I.. -I..\.. /DSHAPELIB_DLLEXPORT

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



