
OBJ	=	ogrelasticdriver.obj ogrelasticdatasource.obj ogrelasticlayer.obj
EXTRAFLAGS =	-DHAVE_CURL $(CURL_CFLAGS) $(CURL_INC) -I.. -I..\..  -I..\geojson

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



