import "../geometryidl.idl";

[
  uuid(bc518ff2-08dd-11d3-b3f9-0080c8e62564),
  version(1.0),
  helpstring("OGR OpenGIS Simple Features 1.0 Type Library")
]

library OGRGeometry
{
    // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}

    importlib("stdole2.tlb");

    interface IPoint;

    // ----------------------------------------------------------------------
    [
      uuid(bc518ff0-08dd-11d3-b3f9-0080c8e62564),
      helpstring("GeometryFactory Class")
    ]
    coclass GeometryFactory {
        [default] interface IGeometryFactory;
    };
};
