
LL_OBJ	=	kml.obj kmlvector.obj ogr2kmlgeometry.obj kmlnode.obj
OGR_OBJ	=	ogrkmldriver.obj ogrkmldatasource.obj ogrkmllayer.obj

OBJ	=	$(LL_OBJ) $(OGR_OBJ)

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

!IFDEF EXPAT_DIR
EXTRAFLAGS =	-I.. -I..\.. $(EXPAT_INCLUDE) -DHAVE_EXPAT=1 
!ELSE
EXTRAFLAGS =	-I.. -I..\.. -DHAVE_EXPAT=0
!ENDIF


default:	$(OBJ)

clean:
	-del *.lib
	-del *.obj *.pdb