
OBJ	=	ogrrecdriver.obj ogrrecdatasource.obj ogrreclayer.obj \
		ll_recio.obj

EXTRAFLAGS =	-I.. -I..\..

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



