
OBJ	=	ogrxplanedriver.obj ogrxplanedatasource.obj ogrxplanelayer.obj ogr_xplane_geo_utils.obj \
		ogr_xplane_reader.obj ogr_xplane_apt_reader.obj ogr_xplane_nav_reader.obj \
		ogr_xplane_fix_reader.obj ogr_xplane_awy_reader.obj

EXTRAFLAGS =	-I.. -I..\.. 

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



