OBJ	=	gnm_wrap.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt
CFLAGS=$(CFLAGS) -DSWIG_NOARRAYS        # needed for Swig 2.0.4 and earlier

default:	$(OBJ)
	xcopy /D  /Y *.obj ..

clean:
	-del *.obj
	-del *.cs
	-del *.cpp

.cpp.obj:	
	$(CC) $(CFLAGS) $(JAVA_INCLUDE) /c $*.cpp
