# Also see https://www.gitpod.io/docs/config-gitpod-file

# Enable only one image
image:
  # Default osgeo image (same as ubuntu-full-latest)
  file: docker/gitpod/osgeo-gdal.Dockerfile

  # Ubuntu small
  #f1ile: docker/gitpod/ubuntu-small-latest.Dockerfile

  # Gitpod's default full workspace
  #file: docker/gitpod/gitpod-workspace-full.Dockerfile
