# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"

  jobs:
    post_checkout:
      - (git --no-pager log --pretty="tformat:%s -- %b" -1 | grep -viqP "skip ci|ci skip") || exit 183
    pre_build:
      - ./doc/rtd/pre_build.sh

  apt_packages:
    - cmake
    - doxygen
    - g++
    - libproj-dev
    - python3
    - python3-pip
    - swig


formats:
  - htmlzip
  - pdf

conda:
  environment: doc/environment.yml

sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: false
