
OBJ	=	vrtdataset.obj vrtrasterband.obj vrtdriver.obj \
		vrtsources.obj vrtfilters.obj vrtsourcedrasterband.obj \
		vrtrawrasterband.obj vrtwarped.obj

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	copy *.obj ..\o

clean:
	-del *.obj

