
OBJ	=	grddataset.obj grcdataset.obj northwood.obj

EXTRAFLAGS = 	-I..\..\ogr\ogrsf_frmts

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

