GDAL_ROOT	=	..

!INCLUDE ..\nmake.opt

VB6_GDAL_DLL =	gdalvb.dll
OBJ	=	vb6_support.obj

default:	$(OBJ)

$(VB6_GDAL_DLL):	$(OBJ)
	link /dll /debug $(OBJ) ../gdal_i.lib /out:$(VB6_GDAL_DLL)
	copy $(VB6_GDAL_DLL) D:\local\bin

clean:	
	-del vb6_support.obj
