name: Delete untagged containers

on:
    push:
        paths-ignore:
            - 'doc/**'
            - 'docker/**'
        branches-ignore:
            - 'backport**'
            - 'dependabot**'

permissions:
  contents: read

jobs:
  delete-untagged-containers:
    name: Delete all containers from gdal-deps without tags
    runs-on: ubuntu-latest
    if: github.repository == 'OSGeo/gdal'
    steps:
    - name: Delete all containers from gdal-deps without tags
      uses: Chizkiyahu/delete-untagged-ghcr-action@b302990b6c629f3b272a31f3c3a268e1f7d0ffae # v4.0.1
      with:
        token: ${{ secrets.PAT_TOKEN_DELETE_UNTAGGED_CONTAINERS }}
        repository_owner: ${{ github.repository_owner }}
        repository: ${{ github.repository }}
        package_name: gdal-deps
        untagged_only: true
        owner_type: org
