cl /c /Ilibtiff /Ilibgeotiff /Iport geoextra.c
cl /c /Ilibtiff /Ilibgeotiff /Iport imggeotiff.c
cl /c /Ilibtiff /Ilibgeotiff /Iport hfaband.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport hfadictionary.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport hfaentry.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport hfafield.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport hfaopen.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport hfatype.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport img2tif.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport rawblockedimage.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport tif_overview.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport port/cpl_conv.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport port/cpl_error.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport port/cpl_string.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport port/cpl_vsisimple.cpp
cl /c /Ilibtiff /Ilibgeotiff /Iport libgeotiff/geo_free.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libgeotiff/geo_get.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libgeotiff/geo_names.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libgeotiff/geo_new.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libgeotiff/geo_print.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libgeotiff/geo_set.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libgeotiff/geo_tiffp.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libgeotiff/geo_write.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libgeotiff/xtiff.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_aux.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_close.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_codec.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_compress.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_dir.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_dirinfo.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_dirread.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_dirwrite.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_dumpmode.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_error.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_fax3.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_fax3sm.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_flush.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_getimage.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_jpeg.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_luv.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_lzw.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_next.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_open.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_packbits.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_pixarlog.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_predict.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_print.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_read.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_strip.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_swab.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_thunder.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_tile.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_unix.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_version.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_warning.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_write.c
cl /c /Ilibtiff /Ilibgeotiff /Iport libtiff/tif_zip.c
cl *.obj /Feimg2tif.exe
