
OBJ =	ogrflatgeobufdataset.obj ogrflatgeobuflayer.obj packedrtree.obj
EXTRAFLAGS =	-I. -I.. -I..\..

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	
clean:
	-del *.obj *.pdb
