
OBJ	=	postgisrasterdataset.obj postgisrasterrasterband.obj postgisrasterdriver.obj

EXTRAFLAGS = -I ../mem -I ../vrt -I$(PG_INC_DIR)

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

