
LL_OBJ	=	gmlpropertydefn.obj gmlfeatureclass.obj gmlfeature.obj \
		gmlreader.obj
OGR_OBJ	=	gml2ogrgeometry.obj ogr2gmlgeometry.obj \
		ogrgmldriver.obj ogrgmldatasource.obj ogrgmllayer.obj

OBJ	=	$(LL_OBJ) $(OGR_OBJ)

EXTRAFLAGS =	-I.. -I..\.. -DHAVE_XERCES=0

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.lib
	-del *.obj *.pdb




