
OBJ	=	wktrasterdataset.obj wktrasterrasterband.obj wktrasterwrapper.obj

EXTRAFLAGS =  -I$(PG_INC_DIR)

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

