/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.27
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gdal.gdal;

public class SWIGTYPE_p_GByte {
  private long swigCPtr;

  protected SWIGTYPE_p_GByte(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_GByte() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_GByte obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

