
BOBJ	=	sdtsiref.obj sdtscatd.obj sdtslinereader.obj sdtslib.obj \
		sdtspointreader.obj sdtsattrreader.obj sdtstransfer.obj \
		sdtspolygonreader.obj sdtsxref.obj sdtsrasterreader.obj \
		sdtsindexedreader.obj 
OBJ 	=	sdtsdataset.obj $(BOBJ)

EXTRAFLAGS = 	-I..\iso8211

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	copy *.obj ..\o

base:	    $(BOBJ)

clean:
	del *.obj

