FROM ubuntu:24.04@sha256:6e75a10070b0fcb0bead763c5118a369bc7cc30dfc1b0749c491bbb21f15c3c7

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --allow-unauthenticated \
    autoconf \
    automake \
    bash \
    ccache \
    cmake \
    clang \
    curl \
    doxygen \
    fossil \
    g++ \
    git \
    gpsbabel \
    jq \
    libblosc-dev \
    libboost-dev \
    libcairo2-dev \
    libcfitsio-dev \
    libcrypto++-dev \
    libcurl4-gnutls-dev \
    libexpat-dev \
    libfcgi-dev \
    libfyba-dev \
    libfreexl-dev \
    libgeos-dev \
    libgeotiff-dev \
    libgif-dev \
    libhdf4-alt-dev \
    libhdf5-serial-dev \
    libjpeg-dev \
    libjxl-dev \
    libkml-dev \
    liblcms2-2 \
    liblz4-dev \
    liblzma-dev \
    libmuparser-dev \
    libmysqlclient-dev \
    libnetcdf-dev \
    libopenexr-dev \
    libopenjp2-7-dev \
    libpcre3-dev \
    libpng-dev \
    libpq-dev \
    libproj-dev \
    librasterlite2-dev \
    libspatialite-dev \
    libssl-dev \
    libwebp-dev \
    libxerces-c-dev \
    libxml2-dev \
    libxslt-dev \
    libzstd-dev \
    locales \
    mysql-client-core-8.0 \
    netcdf-bin \
    openjdk-8-jdk-headless \
    poppler-utils \
    postgis \
    postgresql-client \
    python3-dev \
    python3-numpy \
    python3-pip \
    sqlite3 \
    swig \
    unixodbc-dev \
    wget \
    zip

# Removing "libpoppler-dev libpoppler-private-dev" from above list to build from source

# do a build of poppler master because their C++ API is unstable
RUN git clone --depth 1 https://gitlab.freedesktop.org/poppler/poppler.git poppler && \
    cd poppler && \
    mkdir build && \
    cd build && \
    cmake -DENABLE_UNSTABLE_API_ABI_HEADER=ON -DENABLE_NSS3=OFF -DENABLE_GPGME=OFF -DENABLE_QT5=OFF -DENABLE_QT6=OFF .. && \
    make -j$(nproc) && \
    make install

# libavif development build
RUN apt-get install -y --allow-unauthenticated libaom-dev libyuv-dev
RUN git clone --depth 1 https://github.com/AOMediaCodec/libavif.git libavif-git && \
    cd libavif-git && \
    mkdir build && \
    cd build && \
    cmake -DAVIF_CODEC_AOM=SYSTEM .. && \
    make -j$(nproc) && \
    make install

# libheif development build
RUN apt-get install -y --allow-unauthenticated libaom-dev libbrotli-dev libde265-dev libx265-dev
RUN git clone --depth 1 https://github.com/strukturag/libheif.git libheif-git && \
    cd libheif-git && \
    mkdir build && \
    cd build && \
    cmake --preset=develop .. && \
    make -j$(nproc) && \
    make install

# MSSQL: client side
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | tee /etc/apt/sources.list.d/msprod.list
RUN apt-get update \
   && ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev

# Build mongo-c-driver
ARG MONGO_C_DRIVER_VERSION=2.1.2
RUN mkdir mongo-c-driver \
    && wget -q https://github.com/mongodb/mongo-c-driver/releases/download/${MONGO_C_DRIVER_VERSION}/mongo-c-driver-${MONGO_C_DRIVER_VERSION}.tar.gz -O - \
        | tar xz -C mongo-c-driver --strip-components=1 \
    && cd mongo-c-driver \
    && mkdir build_cmake \
    && cd build_cmake \
    && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_TESTS=NO -DCMAKE_BUILD_TYPE=Release \
    && make -j$(nproc) \
    && make install \
    && cd ../.. \
    && rm -rf mongo-c-driver

# Build mongocxx
ARG MONGOCXX_VERSION=4.1.4
RUN mkdir mongocxx \
    && wget -q https://github.com/mongodb/mongo-cxx-driver/archive/r${MONGOCXX_VERSION}.tar.gz -O - \
        | tar xz -C mongocxx --strip-components=1 \
    && cd mongocxx \
    && mkdir build_cmake \
    && cd build_cmake \
    && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_TESTS=OFF -DMONGOCXX_ENABLE_SLOW_TESTS=NO -DCMAKE_BUILD_TYPE=Release -DBUILD_VERSION=${MONGOCXX_VERSION} \
    && make -j$(nproc) \
    && make install \
    && cd ../.. \
    && rm -rf mongocxx

# Build libOpenDRIVE
ARG OPENDRIVE_VERSION=0.6.0-gdal
RUN if test "${OPENDRIVE_VERSION}" != ""; then ( \
    wget -q https://github.com/DLR-TS/libOpenDRIVE/archive/refs/tags/${OPENDRIVE_VERSION}.tar.gz \
    && tar xzf ${OPENDRIVE_VERSION}.tar.gz \
    && rm -f ${OPENDRIVE_VERSION}.tar.gz \
    && cd libOpenDRIVE-${OPENDRIVE_VERSION} \
    && cmake . -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/ \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf libOpenDRIVE-${OPENDRIVE_VERSION} \
    ); fi

# ESRI File Geodatabase API
RUN curl -L -O https://github.com/Esri/file-geodatabase-api/raw/master/FileGDB_API_1.5/FileGDB_API_1_5_64gcc51.tar.gz \
	&& tar xzf FileGDB_API_1_5_64gcc51.tar.gz \
	&& cp -r FileGDB_API-64gcc51/* /usr/ \
	&& rm FileGDB_API_1_5_64gcc51.tar.gz \
	&& rm -rf FileGDB_API-64gcc51 \
	&& ldconfig

# Oracle : client side (proprietary software)
RUN curl -L -O https://download.oracle.com/otn_software/linux/instantclient/199000/instantclient-basic-linux.x64-19.9.0.0.0dbru.zip \
    && curl -L -O https://download.oracle.com/otn_software/linux/instantclient/199000/instantclient-sdk-linux.x64-19.9.0.0.0dbru.zip \
    && unzip instantclient-basic-linux.x64-19.9.0.0.0dbru.zip -d /opt \
    && unzip instantclient-sdk-linux.x64-19.9.0.0.0dbru.zip -d opt \
    && apt-get install -y libaio1t64 \
    && ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1

COPY requirements.txt /tmp/
RUN PYTHON_CMD=python3 && $PYTHON_CMD -m pip install -U --break-system-packages -r /tmp/requirements.txt

# cfchecker requires udunits2
RUN apt-get install -y --allow-unauthenticated libudunits2-0 libudunits2-data
RUN PYTHON_CMD=python3 && $PYTHON_CMD -m pip install --break-system-packages cfchecker

RUN PYTHON_CMD=python3 && $PYTHON_CMD -m pip install --break-system-packages fsspec

# Manually install ADBC packages from Ubuntu 22.04 as there are no 24.04 packages at time of writing.
RUN curl -LO -fsS https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow-adbc/libadbc-driver-manager102_14-1_amd64.deb \
    && curl -LO -fsS https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow-adbc/libadbc-driver-manager-dev_14-1_amd64.deb \
    && curl -LO -fsS https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow-adbc/libadbc-driver-sqlite102_14-1_amd64.deb \
    && curl -LO -fsS https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow-adbc/libadbc-driver-sqlite-dev_14-1_amd64.deb \
    && curl -LO -fsS https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow-adbc/libadbc-driver-snowflake102_14-1_amd64.deb \
    && curl -LO -fsS https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow-adbc/libadbc-driver-snowflake-dev_14-1_amd64.deb \
    && dpkg -i libadbc-driver-manager102_14-1_amd64.deb \
    && dpkg -i libadbc-driver-manager-dev_14-1_amd64.deb \
    && dpkg -i libadbc-driver-sqlite102_14-1_amd64.deb \
    && dpkg -i libadbc-driver-sqlite-dev_14-1_amd64.deb \
    && dpkg -i libadbc-driver-snowflake102_14-1_amd64.deb \
    && dpkg -i libadbc-driver-snowflake-dev_14-1_amd64.deb

# Install libduckdb
RUN curl -LO -fsS https://github.com/duckdb/duckdb/releases/download/v1.1.3/libduckdb-linux-amd64.zip \
    && unzip libduckdb-linux-amd64.zip libduckdb.so \
    && mv libduckdb.so /usr/lib/x86_64-linux-gnu \
    && rm -f libduckdb-linux-amd64.zip

# Build Arrow git HEAD

RUN curl -LO -fsS https://github.com/apache/arrow/archive/refs/heads/main.zip \
    && unzip main.zip \
    && cd arrow-main/cpp \
    && mkdir build \
    && cd build \
    && cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=/usr \
                -DARROW_BUILD_STATIC=OFF \
                -DARROW_ACERO=ON \
                -DARROW_DATASET=ON \
                -DARROW_PARQUET=ON \
                -DARROW_WITH_BZ2=ON \
                -DARROW_WITH_LZ4=ON \
                -DARROW_WITH_SNAPPY=ON \
                -DARROW_WITH_ZLIB=ON \
                -DARROW_WITH_ZSTD=ON \
    && make -j$(nproc) \
    && make install \
    && cd ../../.. \
    && rm -rf arrow-main

# Install pdfium
RUN wget -q https://github.com/rouault/pdfium_build_gdal_3_12/releases/download/pdfium_7391_v1/install-ubuntu2004-rev7391.tar.gz \
  && tar -xzf install-ubuntu2004-rev7391.tar.gz \
  && chown -R root:root install \
  && mv install/lib/* /usr/lib/ \
  && mv install/include/* /usr/include/ \
  && rm -rf install-ubuntu2004-rev7391.tar.gz install

