

OBJ	=	aigopen.o gridlib.o aigccitt.o \
		cpl_vsisimple.o cpl_conv.o cpl_error.o

default:	aitest

aitest:	$(OBJ)
	$(CXX) aitest.c $(OBJ) -o aitest

cpl_vsisimple.o:	cpl_vsisimple.cpp
	$(CXX) -c cpl_vsisimple.cpp

cpl_conv.o:	cpl_conv.cpp
	$(CXX) -c cpl_conv.cpp

cpl_error.o:	cpl_error.cpp
	$(CXX) -c cpl_error.cpp

