OBJ     =       ogrgtmdriver.obj ogrgtmdatasource.obj ogrgtmlayer.obj gtm.obj gtmwaypointlayer.obj gtmtracklayer.obj
EXTRAFLAGS =	-I.. -I..\..

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb
