# $Id$
#
# Makefile to build zlib using NMAKE and Visual C++ compiler.
#
OBJ = \
    adler32.obj \
    compress.obj \
    crc32.obj \
    deflate.obj \
    gzio.obj \
    infback.obj \
    inffast.obj \
    inflate.obj \
    inftrees.obj \
    trees.obj \
    uncompr.obj \
    zutil.obj

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS = $(SOFTWARNFLAGS) -Dverbose=-1 /wd4131

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

