
EXTRAFLAGS = 	-I$(ECWDIR)\include /DWIN32 -DFRMT_ecw

OBJ	=	ecwdataset.obj ecwcreatecopy.obj

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	copy *.obj ..\o

all:	default testecw.exe

clean:
	-del *.obj
	-del *.exe

testecw.exe:	testecw.cpp
	$(CC) /Zi /MD $(EXTRAFLAGS) testecw.cpp $(ECWLIB)

ecw_example1.exe:	ecw_example1.c
	$(CC) /MD $(EXTRAFLAGS) ecw_example1.c $(ECWLIB)
	

