
OBJ	=	ogrselafindriver.obj ogrselafindatasource.obj ogrselafinlayer.obj io_selafin.obj
EXTRAFLAGS =	-I.. -I..\..

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



