
OBJ	=	mbtilesdataset.obj

EXTRAFLAGS = -I../../ogr -I../../ogr/ogrsf_frmts/geojson -I../zlib

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

