
OBJ	=	ogrogdidriver.obj ogrogdidatasource.obj ogrogdilayer.obj

EXTRAFLAGS =	-I.. -I..\.. \
		-I$(OGDIDIR)/include/ogdi -I$(OGDIDIR)/include/win32 \
		-I$(OGDIDIR)/proj -I(OGDIDIR)/include -DWIN32 -D_WINDOWS

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



