GDAL_ROOT = ..\..

DIRLIST = generic shape mitab

!INCLUDE $(GDAL_ROOT)\nmake-wince.opt

default:
	for %d in ( $(DIRLIST) ) do \
		cd %d \
		&& $(MAKE) /f makefile.evc4 \
		&& cd ..

	lib /out:ogrsf_frmts.lib generic\*.obj shape\*.obj mitab\*.obj 

clean:
	-del ogrsf_frmts.lib
	for %d in ( $(DIRLIST) ) do \
		cd %d \
		&& $(MAKE) /f makefile.evc4 clean \
		&& cd ..

html-install:
	copy *.html $(HTMLDIR)
	-for %d in ( $(DIRLIST) ) do \
		copy %d\drv_*.html $(HTMLDIR)
