OBJ	=	gdalconst_wrap.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..

clean:
	-del *.obj
	-del *.cs
	-del *.cpp

.cpp.obj:	
	$(CC) $(CFLAGS) $(JAVA_INCLUDE) /c $*.cpp

