
OBJ	=	rmfdataset.obj rmfdem.obj rmfjpeg.obj rmflzw.obj

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

!IFDEF JPEG_SUPPORTED
EXTRAFLAGS =	-DHAVE_LIBJPEG
!ENDIF

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

