FROM alpine:edge@sha256:732b6226a359f67fad4e38b34dd374bd62a6d282e20c493a38cc7d3a653f86ca

RUN apk add \
    apache-arrow-dev \
    armadillo-dev \
    basisu-dev \
    blosc-dev \
    brunsli-dev \
    ccache \
    cfitsio-dev \
    cmake \
    curl-dev \
    expat-dev \
    freexl-dev \
    gcc \
    g++ \
    geos-dev \
    giflib-dev \
    gnu-libiconv-dev \
    hdf5-dev \
    json-c-dev \
    kealib-dev \
    libaec-dev \
    libarchive-dev \
    libavif-dev \
    libdeflate-dev \
    libgeotiff-dev \
    libheif-dev \
    libjpeg-turbo-dev \
    libjxl-dev \
    libkml-dev \
    libpng-dev \
    libpq-dev \
    librasterlite2-dev \
    libspatialite-dev \
    libtirpc-dev \
    libwebp-dev \
    libxml2-dev \
    libxslt-dev \
    linux-headers \
    lz4-dev \
    make \
    mariadb-connector-c-dev \
    muparser-dev \
    netcdf-dev \
    odbc-cpp-wrapper-dev \
    ogdi-dev \
    openexr-dev \
    openjpeg-dev \
    openssl-dev \
    pcre2-dev \
    podofo-dev \
    poppler-dev \
    proj-dev \
    proj-util \
    py3-pyarrow \
    py3-pyarrow-pyc \
    py3-numpy \
    py3-numpy-dev \
    py3-pip \
    py3-setuptools \
    python3-dev \
    qhull-dev \
    sfcgal-dev \
    snappy-dev \
    sqlite-dev \
    tiledb-dev \
    tiff-dev \
    unixodbc-dev \
    xerces-c-dev \
    xz-dev \
    zlib-dev \
    zstd-dev

COPY requirements.txt /tmp/
RUN PYTHON_CMD=python3 && $PYTHON_CMD -m pip install --break-system-packages -U -r /tmp/requirements.txt

RUN apk add git autoconf automake libtool bison && \
    git clone --branch "${SWIG_GIT_TAG:-master}" --depth 1 https://github.com/swig/swig.git swig-git && \
    cd swig-git && \
    ./autogen.sh && \
    ./configure --prefix=/usr && \
    make -j$(nproc) && \
    make install
