
OBJ	=	ogrbnadriver.obj ogrbnadatasource.obj ogrbnalayer.obj \
		ogrbnaparser.obj

EXTRAFLAGS =	-I.. -I..\..

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



