
OBJ	=	ogrcaddriver.obj gdalcaddataset.obj ogrcadlayer.obj vsilfileio.obj

EXTRAFLAGS =	-I.. -I..\.. -Ilibopencad $(SOFTWARNFLAGS) -DOCAD_EXTERN=""

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	cd libopencad
	$(MAKE) /f makefile.vc
	cd ..

clean:
	cd libopencad
	$(MAKE) /f makefile.vc clean
	cd ..
	-del *.lib
	-del *.obj *.pdb

