
GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

OBJ	=	netcdfdataset.obj gmtdataset.obj
EXTRAFLAGS = 	/I$(NETCDF_INC_DIR)

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

plugin:	gdal_NETCDF.dll

gdal_NETCDF.dll: $(OBJ)
	link /dll /out:gdal_NETCDF.dll $(OBJ) \
		$(GDALLIB) $(NETCDF_LIB)
	if exist gdal_NETCDF.dll.manifest mt -manifest gdal_NETCDF.dll.manifest -outputresource:gdal_NETCDF.dll;2