
OBJ	=	ogrpcidskdriver.obj ogrpcidskdatasource.obj ogrpcidsklayer.obj

EXTRAFLAGS =	-I.. -I..\.. $(PCIDSK_INC) -I..\..\..\frmts\pcidsk\sdk

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



