/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Driver : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Driver(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Driver obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      throw new MethodAccessException("C++ destructor does not have public access");
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public string name {
    get {
      string ret = ogrPINVOKE.get_Driver_name(swigCPtr);
      return ret;
    } 
  }

  public DataSource CreateDataSource(string name, SWIGTYPE_p_p_char options) {
    IntPtr cPtr = ogrPINVOKE.Driver_CreateDataSource(swigCPtr, name, SWIGTYPE_p_p_char.getCPtr(options));
    DataSource ret = (cPtr == IntPtr.Zero) ? null : new DataSource(cPtr, true);
    return ret;
  }

  public DataSource CopyDataSource(DataSource copy_ds, string name, SWIGTYPE_p_p_char options) {
    IntPtr cPtr = ogrPINVOKE.Driver_CopyDataSource(swigCPtr, DataSource.getCPtr(copy_ds), name, SWIGTYPE_p_p_char.getCPtr(options));
    DataSource ret = (cPtr == IntPtr.Zero) ? null : new DataSource(cPtr, true);
    return ret;
  }

  public DataSource Open(string name, int update) {
    IntPtr cPtr = ogrPINVOKE.Driver_Open(swigCPtr, name, update);
    DataSource ret = (cPtr == IntPtr.Zero) ? null : new DataSource(cPtr, true);
    return ret;
  }

  public int DeleteDataSource(string name) {
    int ret = ogrPINVOKE.Driver_DeleteDataSource(swigCPtr, name);
    return ret;
  }

  public int TestCapability(string cap) {
    int ret = ogrPINVOKE.Driver_TestCapability(swigCPtr, cap);
    return ret;
  }

  public string GetName() {
    string ret = ogrPINVOKE.Driver_GetName(swigCPtr);
    return ret;
  }

}
