/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class MajorObject : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MajorObject(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MajorObject obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      throw new MethodAccessException("C++ destructor does not have public access");
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public string GetDescription() {
    string ret = gdalPINVOKE.MajorObject_GetDescription(swigCPtr);
    return ret;
  }

  public void SetDescription(string pszNewDesc) {
    gdalPINVOKE.MajorObject_SetDescription(swigCPtr, pszNewDesc);
  }

  public SWIGTYPE_p_p_char GetMetadata_Dict(string pszDomain) {
    IntPtr cPtr = gdalPINVOKE.MajorObject_GetMetadata_Dict(swigCPtr, pszDomain);
    SWIGTYPE_p_p_char ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_p_char GetMetadata_List(string pszDomain) {
    IntPtr cPtr = gdalPINVOKE.MajorObject_GetMetadata_List(swigCPtr, pszDomain);
    SWIGTYPE_p_p_char ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
    return ret;
  }

  public int SetMetadata(SWIGTYPE_p_p_char papszMetadata, string pszDomain) {
    int ret = gdalPINVOKE.MajorObject_SetMetadata__SWIG_0(swigCPtr, SWIGTYPE_p_p_char.getCPtr(papszMetadata), pszDomain);
    return ret;
  }

  public int SetMetadata(string pszMetadataString, string pszDomain) {
    int ret = gdalPINVOKE.MajorObject_SetMetadata__SWIG_1(swigCPtr, pszMetadataString, pszDomain);
    return ret;
  }

}
