
OBJ	=	mrsiddataset.obj

EXTRAFLAGS = 	-I$(MRSID_INCLUDE) -I..\gtiff\libgeotiff $(MRSID_FLAGS)

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	copy *.obj ..\o

clean:
	-del *.obj


