#!/usr/bin/env pytest
###############################################################################
# $Id$
#
# Project:  GDAL/OGR Test Suite
# Purpose:  Test ELAS driver
# Author:   Even Rouault, <even dot rouault at spatialys.com>
#
###############################################################################
# Copyright (c) 2009, Even Rouault <even dot rouault at spatialys.com>
#
# SPDX-License-Identifier: MIT
###############################################################################


import gdaltest

###############################################################################
# Test a dataset generated by Create()


def test_elas_1():

    tst = gdaltest.GDALTest("ELAS", "elas/byte_elas.bin", 1, 4672)
    tst.testOpen()


###############################################################################
# Test Create()


def test_elas_2():

    tst = gdaltest.GDALTest("ELAS", "elas/byte_elas.bin", 1, 4672)
    tst.testCreate()
