GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

OBJ	=	hdf4dataset.obj hdf4imagedataset.obj

EXTRAFLAGS = 	-I..\pds -I$(HDF4_DIR)\include -Ihdf-eos -DFRMT_hdf4 

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o
	cd  hdf-eos
	$(MAKE) /f makefile.vc

clean:
	-del *.obj
	cd hdf-eos
	$(MAKE) /f makefile.vc clean
	cd ..
