name: gdal-docs
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - breathe
    - recommonmark
    - sphinx
    - sphinx-bootstrap-theme
    - sphinx-markdown-tables
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
    - sphinxcontrib-jquery
    - sphinxcontrib-spelling
