
OBJ	=	ogdidataset.obj 

GDAL_ROOT	=	..\..

EXTRAFLAGS	=	-I$(OGDIDIR)/ogdi/include -I$(OGDIDIR)/include/win32 \
			-I$(OGDIDIR)/proj -DWIN32 -D_WINDOWS

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

