
OBJ	=	ogrgpxdriver.obj ogrgpxdatasource.obj ogrgpxlayer.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

!IFDEF EXPAT_DIR
OBJ	=	$(EXPAT_OBJ) $(OGR_OBJ)
EXTRAFLAGS =	-I.. -I..\.. $(EXPAT_INCLUDE) -DHAVE_EXPAT=1 
!ELSE
OBJ	=	$(OGR_OBJ)
EXTRAFLAGS =	-I.. -I..\..
!ENDIF

default:	$(OBJ)

clean:
	-del *.obj *.pdb



