
OBJ	=	jpeg2000dataset.obj

EXTRAFLAGS = 	-I..\iso8211 $(JASPER_INCLUDE) /DWIN32 -DFRMT_jpeg2000

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	copy *.obj ..\o

clean:
	-del *.obj

