
OBJ	=	dted_api.obj dteddataset.obj dted_create.obj dted_create.obj \
		dted_ptstream.obj

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

dted_test.exe:	dted_test.obj $(OBJ)
	cl dted_test.obj dted_api.obj dted_create.obj dted_ptstream.obj \
		..\..\port\cpl.lib

