
OBJ	=	pdsdataset.obj isis2dataset.obj isis3dataset.obj \
		vicardataset.obj nasakeywordhandler.obj vicarkeywordhandler.obj

GDAL_ROOT	=	..\..

EXTRAFLAGS = 	-I..\raw

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

