/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OGR {

using System;

public class Feature : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal Feature(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(Feature obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  protected Feature() : this(IntPtr.Zero, false) {
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      throw new MethodAccessException("C++ destructor does not have public access");
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public Feature(FeatureDefn feature_def) : this(ogrPINVOKE.new_Feature(FeatureDefn.getCPtr(feature_def)), true) {
  }

  public void Destroy() {
    ogrPINVOKE.Feature_Destroy(swigCPtr);
  }

  public FeatureDefn GetDefnRef() {
    IntPtr cPtr = ogrPINVOKE.Feature_GetDefnRef(swigCPtr);
    return (cPtr == IntPtr.Zero) ? null : new FeatureDefn(cPtr, false);
  }

  public int SetGeometry(Geometry geom) {
    return ogrPINVOKE.Feature_SetGeometry(swigCPtr, Geometry.getCPtr(geom));
  }

  public int SetGeometryDirectly(Geometry geom) {
    return ogrPINVOKE.Feature_SetGeometryDirectly(swigCPtr, Geometry.getCPtr(geom));
  }

  public Geometry GetGeometryRef() {
    IntPtr cPtr = ogrPINVOKE.Feature_GetGeometryRef(swigCPtr);
    return (cPtr == IntPtr.Zero) ? null : new Geometry(cPtr, false);
  }

  public Feature Clone() {
    IntPtr cPtr = ogrPINVOKE.Feature_Clone(swigCPtr);
    return (cPtr == IntPtr.Zero) ? null : new Feature(cPtr, true);
  }

  public int Equal(Feature feature) {
    return ogrPINVOKE.Feature_Equal(swigCPtr, Feature.getCPtr(feature));
  }

  public int GetFieldCount() {
    return ogrPINVOKE.Feature_GetFieldCount(swigCPtr);
  }

  public FieldDefn GetFieldDefnRef(int id) {
    IntPtr cPtr = ogrPINVOKE.Feature_GetFieldDefnRef__SWIG_0(swigCPtr, id);
    return (cPtr == IntPtr.Zero) ? null : new FieldDefn(cPtr, true);
  }

  public FieldDefn GetFieldDefnRef(string name) {
    IntPtr cPtr = ogrPINVOKE.Feature_GetFieldDefnRef__SWIG_1(swigCPtr, name);
    return (cPtr == IntPtr.Zero) ? null : new FieldDefn(cPtr, true);
  }

  public string GetFieldAsString(int id) {
    return ogrPINVOKE.Feature_GetFieldAsString__SWIG_0(swigCPtr, id);
  }

  public string GetFieldAsString(string name) {
    return ogrPINVOKE.Feature_GetFieldAsString__SWIG_1(swigCPtr, name);
  }

  public int GetFieldAsInteger(int id) {
    return ogrPINVOKE.Feature_GetFieldAsInteger__SWIG_0(swigCPtr, id);
  }

  public int GetFieldAsInteger(string name) {
    return ogrPINVOKE.Feature_GetFieldAsInteger__SWIG_1(swigCPtr, name);
  }

  public double GetFieldAsDouble(int id) {
    return ogrPINVOKE.Feature_GetFieldAsDouble__SWIG_0(swigCPtr, id);
  }

  public double GetFieldAsDouble(string name) {
    return ogrPINVOKE.Feature_GetFieldAsDouble__SWIG_1(swigCPtr, name);
  }

  public int IsFieldSet(int id) {
    return ogrPINVOKE.Feature_IsFieldSet__SWIG_0(swigCPtr, id);
  }

  public int IsFieldSet(string name) {
    return ogrPINVOKE.Feature_IsFieldSet__SWIG_1(swigCPtr, name);
  }

  public int GetFieldIndex(string name) {
    return ogrPINVOKE.Feature_GetFieldIndex(swigCPtr, name);
  }

  public int GetFID() {
    return ogrPINVOKE.Feature_GetFID(swigCPtr);
  }

  public int SetFID(int fid) {
    return ogrPINVOKE.Feature_SetFID(swigCPtr, fid);
  }

  public void DumpReadable() {
    ogrPINVOKE.Feature_DumpReadable(swigCPtr);
  }

  public void UnsetField(int id) {
    ogrPINVOKE.Feature_UnsetField__SWIG_0(swigCPtr, id);
  }

  public void UnsetField(string name) {
    ogrPINVOKE.Feature_UnsetField__SWIG_1(swigCPtr, name);
  }

  public void SetField(int id, string value) {
    ogrPINVOKE.Feature_SetField__SWIG_0(swigCPtr, id, value);
  }

  public void SetField(string name, string value) {
    ogrPINVOKE.Feature_SetField__SWIG_1(swigCPtr, name, value);
  }

  public int SetFrom(Feature other, int forgiving) {
    return ogrPINVOKE.Feature_SetFrom(swigCPtr, Feature.getCPtr(other), forgiving);
  }

  public string GetStyleString() {
    return ogrPINVOKE.Feature_GetStyleString(swigCPtr);
  }

  public void SetStyleString(string the_string) {
    ogrPINVOKE.Feature_SetStyleString(swigCPtr, the_string);
  }

  public int GetFieldType(int id) {
    return ogrPINVOKE.Feature_GetFieldType__SWIG_0(swigCPtr, id);
  }

  public int GetFieldType(string name, string value) {
    return ogrPINVOKE.Feature_GetFieldType__SWIG_1(swigCPtr, name, value);
  }

}

}
