//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CoverageImpl.rc
//
#define IDS_PROJNAME                    100
#define IDR_BANDMETADATAIMPL            101
#define IDR_GRIDCOVERAGEIMPL            102
#define IDR_MULTIDIMENSIONIMPL          103
#define IDR_RASTERMETADATAIMPL          104
#define IDR_COLORTABLEIMPL              105
#define IDR_GRIDMATRIXVALUESIMPL        106
#define IDR_SPATIALVECTORIMPL           107
#define IDR_SPATIALPOSITIONIMPL         108
#define IDR_ORTHOGEOREFERENCEIMPL       109
#define IDR_AFFINEGEOREFERENCEIMPL      110
#define IDR_GRIDGEOMETRYIMPL            111
#define IDR_GRIDDATAIMPL                112
#define IDR_BANDRATIONINGIMPL           113
#define IDR_DENSITYSLICEIMPL            114
#define IDR_FILTERRASTERMODIFIERIMPL    115
#define IDR_GREYSCALETHRESHOLDIMPL      116
#define IDR_ENHANCERASTERMODIFIERIMPL   117
#define IDR_RASTERMODIFIERFACTORYIMPL   118
#define IDR_GRIDCOVERAGEFACTORYIMPL     119
#define IDR_GEOREFERENCEFACTORYIMPL     120

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           121
#endif
#endif
