
OBJ =	iom_attr.obj iom_basket.obj iom_error.obj \
	iom_file.obj iom_iterator.obj iom_object.obj \
	iom_utilities.obj iom_value.obj \
	reader.obj tags.obj ustrings.obj writer.obj

GDAL_ROOT	=	..\..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS =	-I.. -I..\.. -I..\..\.. $(XERCES_INCLUDE) 

default:	$(OBJ)

clean:
	-del *.lib
	-del *.obj *.pdb

