
OBJ	=	\
	gifdataset.obj

GDAL_ROOT	=	..\..

EXTRAFLAGS = 	-Ilibungif

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	copy *.obj ..\o
	cd libungif
	$(MAKE) /f makefile.vc
	cd ..

clean:
	-del *.obj

