
OBJ	=	ograeronavfaadriver.obj ograeronavfaadatasource.obj ograeronavfaalayer.obj
EXTRAFLAGS =	-I.. -I..\.. -I..\xplane

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



