
OBJ	=	cache.obj dataset.obj datawindow.obj gdalhttp.obj md5.obj minidriver.obj minidriver_wms.obj rasterband.obj stuff.obj wmsdriver.obj

EXTRAFLAGS = 	$(CURL_INC) -DHAVE_CURL

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt


default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj
	-del *.dll
