
OBJ	=	ogridrisidriver.obj ogridrisidatasource.obj ogridrisilayer.obj
EXTRAFLAGS =	-I.. -I..\.. -I..\..\..\frmts\idrisi

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



