
OBJ	=	ogrgmedriver.obj ogrgmedatasource.obj ogrgmelayer.obj ogrgmejson.obj
EXTRAFLAGS =	-I.. -I..\.. -I..\geojson -I..\geojson\libjson

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



