
OBJ	=	sar_ceosdataset.obj \
		ceosrecipe.obj ceossar.obj ceos.obj link.obj 

GDAL_ROOT	=	..\..

EXTRAFLAGS = 	-I..\raw

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	copy *.obj ..\o

clean:
	-del *.obj

