
OBJ	=	argdataset.obj

EXTRAFLAGS  =   -I..\..\ogr\ogrsf_frmts\geojson -I../../ogr/ogrsf_frmts/geojson/libjson -I..\raw

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

