GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

OBJ	=	hdf5dataset.obj  hdf5imagedataset.obj

EXTRAFLAGS = 	-I$(HDF5_DIR)\include -DFRMT_hdf5 -DWIN32 -D_HDF5USEDLL_ 

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

