
OBJ	=	\
	SWapi.obj GDapi.obj EHapi.obj gctp_wrap.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS = 	-I$(HDF4_INCLUDE) -I$(HDF4_DIR)\include -I.\ -I..\ -DFRMT_hdf4 -DWIN32

!IF "$(HDF4_HAS_MAXOPENFILES)" == "YES"
EXTRAFLAGS = $(EXTRAFLAGS) -DHDF4_HAS_MAXOPENFILES
!ENDIF

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\..\o

clean:
	-del *.obj

plugin:	$(OBJ)
