
OBJ	=	\
	SWapi.obj GDapi.obj EHapi.obj gctp_wrap.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS = 	-I$(HDF4_DIR)\include -I.\ -I..\ -DFRMT_hdf4 -DWIN32

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\..\o

clean:
	-del *.obj

