
OBJ	=	rasterlitedataset.obj rasterlitecreatecopy.obj rasterliteoverviews.obj

EXTRAFLAGS = -I../../ogr -I../mem

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

