#
# CPL (Common Portability Library) makefile
#

OBJ	=	cpl_conv.obj \
		cpl_error.obj \
		cpl_string.obj \
		cpl_vsisimple.obj \
		cplgetsymbol.obj \
		cpl_dir.obj \
		cpl_path.obj

LIB	=	cpl.lib

GDAL_ROOT = ..

!INCLUDE ..\nmake.opt

default:	cpl_config.h $(LIB)

$(LIB):	$(OBJ)
	lib /out:cpl.lib *.obj

clean:
	del *.obj *.lib

cpl_config.h:	cpl_config.h.vc
	copy cpl_config.h.vc cpl_config.h


