
GDAL_ROOT	=	..\..

OBJ	=	jpipkakdataset.obj kdu_cache.obj
EXTRAFLAGS = 	-I$(KAKDIR)\apps\support\ -I$(KAKDIR)\apps\compressed_io\ -I$(KAKDIR)\coresys\common\ -I$(KAKDIR)\apps\caching_sources -DKDU_PENTIUM_MSVC /GX

!INCLUDE $(GDAL_ROOT)\nmake.opt


default:	$(OBJ) kakinstall
	xcopy /D  /Y *.obj ..\o

kakinstall:
	copy $(KAKDIR)\obj\*.obj ..\o

kdu_cache.cpp:	  $(KAKDIR)\apps\caching_sources\kdu_cache.cpp
	copy $(KAKDIR)\apps\caching_sources\kdu_cache.cpp 

clean:
	-del *.obj
	-del *.dll
