OBJ	=	reader_digital_globe.obj reader_geo_eye.obj reader_orb_view.obj \
                reader_pleiades.obj reader_rdk1.obj reader_landsat.obj

!INCLUDE ..\..\nmake.opt

EXTRAFLAGS =	-I..\..\port -I..\..\ogr -I..\

default:	$(OBJ)
    xcopy /D  /Y *.obj ..\

clean:
	-del *.obj *.res
