OBJ	=	reader_digital_globe.obj reader_geo_eye.obj reader_orb_view.obj \
                reader_pleiades.obj reader_rdk1.obj reader_landsat.obj \
                reader_spot.obj reader_rapid_eye.obj reader_alos.obj \
                reader_eros.obj reader_kompsat.obj

GDAL_ROOT	=	..\..
                
!INCLUDE ..\..\nmake.opt

EXTRAFLAGS =	-I..\..\port -I..\..\ogr -I..\

default:	$(OBJ)
    xcopy /D  /Y *.obj ..\

clean:
	-del *.obj
