OBJ     =       ogrdxfdriver.obj ogrdxfdatasource.obj ogrdxflayer.obj \
		ogrdxfreader.obj ogrdxf_blockmap.obj ogrdxf_dimension.obj \
		ogrdxfwriterds.obj ogrdxfwriterlayer.obj intronurbs.obj \
		ogrdxf_polyline_smooth.obj ogrdxfblockslayer.obj \
		ogrdxfblockswriterlayer.obj ogrdxf_hatch.obj \
		ogr_autocad_services.obj
        
EXTRAFLAGS =	-I.. -I..\..

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb
