=head1 NAME

osr - A part of the Perl interface to the GDAL library.

=head1 SYNOPSIS

  use osr;

=head1 ABSTRACT

This module is a part of the Perl bindings to the GDAL library. The
GDAL modules allows you to access and manipulate from Perl all
geospatial data that the installed GDAL library is configured to
read/write.

=head1 STATUS

This module is beta quality. As most of the names and calling
conventions come directly from the underlying GDAL library they are
quite stable and will continue to work like the do now. However, many
things could, should, and will be made more perlish.

Generally, those methods which are documented, have been tested. If
the method or constructor you are looking for is not documented,
perhaps there is another way of doing what you want to do.

=head1 PACKAGE METHODS

=over

=item GetWellKnownGeogCSAsWKT

=item GetProjectionMethods

=item GetProjectionMethodParameterList

=item GetProjectionMethodParamInfo

=back

=head1 CONSTANTS

Access as $osr::<constant>

=over

=item SRS_PT_ALBERS_CONIC_EQUAL_AREA

=item SRS_PT_AZIMUTHAL_EQUIDISTANT

=item SRS_PT_CASSINI_SOLDNER

=item SRS_PT_CYLINDRICAL_EQUAL_AREA

=item SRS_PT_ECKERT_IV

=item SRS_PT_ECKERT_VI

=item SRS_PT_EQUIDISTANT_CONIC

=item SRS_PT_EQUIRECTANGULAR

=item SRS_PT_GALL_STEREOGRAPHIC

=item SRS_PT_GNOMONIC

=item SRS_PT_GOODE_HOMOLOSINE

=item SRS_PT_HOTINE_OBLIQUE_MERCATOR

=item SRS_PT_HOTINE_OBLIQUE_MERCATOR_TWO_POINT_NATURAL_ORIGIN

=item SRS_PT_LABORDE_OBLIQUE_MERCATOR

=item SRS_PT_LAMBERT_CONFORMAL_CONIC_1SP

=item SRS_PT_LAMBERT_CONFORMAL_CONIC_2SP

=item SRS_PT_LAMBERT_CONFORMAL_CONIC_2SP_BELGIUM

=item SRS_PT_LAMBERT_AZIMUTHAL_EQUAL_AREA

=item SRS_PT_MERCATOR_1SP

=item SRS_PT_MERCATOR_2SP

=item SRS_PT_MILLER_CYLINDRICAL

=item SRS_PT_MOLLWEIDE

=item SRS_PT_NEW_ZEALAND_MAP_GRID

=item SRS_PT_OBLIQUE_STEREOGRAPHIC

=item SRS_PT_ORTHOGRAPHIC

=item SRS_PT_POLAR_STEREOGRAPHIC

=item SRS_PT_POLYCONIC

=item SRS_PT_ROBINSON

=item SRS_PT_SINUSOIDAL

=item SRS_PT_STEREOGRAPHIC

=item SRS_PT_SWISS_OBLIQUE_CYLINDRICAL

=item SRS_PT_TRANSVERSE_MERCATOR

=item SRS_PT_TRANSVERSE_MERCATOR_SOUTH_ORIENTED

=item SRS_PT_TRANSVERSE_MERCATOR_MI_22

=item SRS_PT_TRANSVERSE_MERCATOR_MI_23

=item SRS_PT_TRANSVERSE_MERCATOR_MI_24

=item SRS_PT_TRANSVERSE_MERCATOR_MI_25

=item SRS_PT_TUNISIA_MINING_GRID

=item SRS_PT_VANDERGRINTEN

=item SRS_PT_KROVAK

=item SRS_PP_CENTRAL_MERIDIAN

=item SRS_PP_SCALE_FACTOR

=item SRS_PP_STANDARD_PARALLEL_1

=item SRS_PP_STANDARD_PARALLEL_2

=item SRS_PP_PSEUDO_STD_PARALLEL_1

=item SRS_PP_LONGITUDE_OF_CENTER

=item SRS_PP_LATITUDE_OF_CENTER

=item SRS_PP_LONGITUDE_OF_ORIGIN

=item SRS_PP_LATITUDE_OF_ORIGIN

=item SRS_PP_FALSE_EASTING

=item SRS_PP_FALSE_NORTHING

=item SRS_PP_AZIMUTH

=item SRS_PP_LONGITUDE_OF_POINT_1

=item SRS_PP_LATITUDE_OF_POINT_1

=item SRS_PP_LONGITUDE_OF_POINT_2

=item SRS_PP_LATITUDE_OF_POINT_2

=item SRS_PP_LONGITUDE_OF_POINT_3

=item SRS_PP_LATITUDE_OF_POINT_3

=item SRS_PP_RECTIFIED_GRID_ANGLE

=item SRS_PP_LANDSAT_NUMBER

=item SRS_PP_PATH_NUMBER

=item SRS_PP_PERSPECTIVE_POINT_HEIGHT

=item SRS_PP_FIPSZONE

=item SRS_PP_ZONE

=item SRS_UL_METER

=item SRS_UL_FOOT

=item SRS_UL_FOOT_CONV

=item SRS_UL_US_FOOT

=item SRS_UL_US_FOOT_CONV

=item SRS_UL_NAUTICAL_MILE

=item SRS_UL_NAUTICAL_MILE_CONV

=item SRS_UL_LINK

=item SRS_UL_LINK_CONV

=item SRS_UL_CHAIN

=item SRS_UL_CHAIN_CONV

=item SRS_UL_ROD

=item SRS_UL_ROD_CONV

=item SRS_DN_NAD27

=item SRS_DN_NAD83

=item SRS_DN_WGS72

=item SRS_DN_WGS84

=item SRS_WGS84_SEMIMAJOR

=item SRS_WGS84_INVFLATTENING

=back

=head1 CLASSES

=head2 osr::SpatialReference

  $srs = new osr::SpatialReference;

=over

=item __str__

=item IsSame

=item IsSameGeogCS

=item IsGeographic

=item IsProjected

=item GetAttrValue

=item SetAttrValue

=item SetAngularUnits

=item GetAngularUnits

=item SetLinearUnits

=item GetLinearUnits

=item GetLinearUnitsName

=item GetAuthorityCode

=item GetAuthorityName

=item SetUTM

=item SetStatePlane

=item AutoIdentifyEPSG

=item SetProjection

=item SetProjParm

=item GetProjParm

=item SetNormProjParm

=item GetNormProjParm

=item SetACEA

=item SetAE

=item SetCS

=item SetBonne

=item SetEC

=item SetEckertIV

=item SetEckertVI

=item SetEquirectangular

=item SetGS

=item SetWellKnownGeogCS

  $cs = 'WGS84'; # an example
  $srs->SetWellKnownGeogCS($cs);

=item SetFromUserInput

=item CopyGeogCSFrom

=item SetTOWGS84

=item GetTOWGS84

=item SetGeogCS

=item SetProjCS

=item ImportFromWkt

=item ImportFromProj4

=item ImportFromESRI

=item ImportFromEPSG

  $nr = 3035; # an example
  $srs->ImportFromEPSG($nr);

=item ImportFromPCI

=item ImportFromUSGS

=item ImportFromXML

=item ExportToWkt

=item ExportToPrettyWkt

=item ExportToProj4

=item ExportToPCI

=item ExportToUSGS

=item ExportToXML

=item CloneGeogCS

=item Validate

=item StripCTParms

=item FixupOrdering

=item Fixup

=item MorphToESRI

=item MorphFromESRI

=back

=head2 osr::CoordinateTransformation

  $transf = new osr::CoordinateTransformation($srs_from, $srs_to);

=over

=item TransformPoint

=back

=head1 KNOWN BUGS

Method named __str__ is a Pythonism and deprecated.

The reference counting scheme is not yet implemented. Make sure that
parents are not deleted before their children! Use "my" a lot.  Do not
give undefined/uninitialized variables to methods.

=head1 SEE ALSO

L<perl>(1), L<gdalconst>(3pm), L<gdal>(3pm), L<ogr>(3pm).

http://www.gdal.org

=head1 AUTHORS

The GDAL bindings team (in alphabetical order):

ari.jolma at tkk.fi
cfis at interserv.com
hobu at iastate.edu
kruland at ku.edu
warmerdam at pobox.com

=head1 COPYRIGHT AND LICENSE

Copyright 2005-2006 by the GDAL bindings team.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Library General Public License for more details.

You should have received a copy of the GNU Library General Public
License along with this library; if not, write to the 
Free Software Foundation, Inc., 59 Temple Place - Suite 330, 
Boston, MA  02111-1307  USA.
