
OBJ	=	hdf4dataset.obj hdf4imagedataset.obj

EXTRAFLAGS = 	-I$(HDF4_DIR)\include -Ihdf-eos -DFRMT_hdf4 

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ) hdf-eos
	copy *.obj ..\o

hdf-eos:
	cd hdf-eos
	$(MAKE) /f makefile.vc
	cd ..
clean:
	-del *.obj hdf-eos\*.obj

