
OBJ	=	hdf4dataset.obj hdf4imagedataset.obj

EXTRAFLAGS = 	-I$(HDF4_DIR)\include -DFRMT_hdf4 

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	copy *.obj ..\o

clean:
	-del *.obj

