
OBJ	=	ogrvrtdriver.obj ogrvrtdatasource.obj ogrvrtlayer.obj \

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS = -I.. -I..\..

default:	$(OBJ)

clean:
	-del *.lib
	-del *.obj *.pdb
	-del *.exe
