
OBJ =	ddfmodule.obj ddfutils.obj ddffielddefn.obj ddfrecord.obj \
	ddffield.obj ddfsubfielddefn.obj

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	copy *.obj ..\o

clean:
	del *.obj

