
!IF "$(OPENJPEG_TRUNK)" == "YES"
OBJ	=	openjpegdataset.obj
!ELSE
OBJ	=	openjpegdataset_opjbranchv2.obj
!ENDIF

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS = $(OPENJPEG_CFLAGS)

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

