
OBJ	=	ogrsfdriverregistrar.obj ogrlayer.obj \
		ogrdatasource.obj ogrsfdriver.obj ogrregisterall.obj

EXTRAFLAGS =	-I.. -I..\..

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



