
OBJ	=	ogrsfdriverregistrar.obj ogrlayer.obj ogr_gensql.obj \
		ogrdatasource.obj ogrsfdriver.obj ogrregisterall.obj


GDAL_ROOT	=	..\..\..

EXTRAFLAGS =	-I.. -I..\.. $(OGDIDEF) $(FMEDEF)

!INCLUDE $(GDAL_ROOT)\nmake.opt

!IFDEF OGDIDIR
OGDIDEF	=	-DOGDI_ENABLED
!ENDIF

!IFDEF FME_DIR
FMEDEF = -DFME_ENABLED
!ENDIF

default:	$(OBJ)

clean:
	-del *.obj *.pdb



