
OBJ	=	ogrsfdriverregistrar.obj ogrlayer.obj \
		ogrdatasource.obj ogrsfdriver.obj ogrregisterall.obj


GDAL_ROOT	=	..\..\..

EXTRAFLAGS =	-I.. -I..\.. $(OGDIDEF)

!INCLUDE $(GDAL_ROOT)\nmake.opt

!IFDEF OGDIDIR
OGDIDEF	=	-DOGDI_ENABLED
!ENDIF

default:	$(OBJ)

clean:
	-del *.obj *.pdb



