

OBJ	=	ogrdb2cli.obj gdaldb2rasterband.obj ogrdb2datasourcemd.obj ogrdb2driver.obj ogrdb2datasource.obj ogrdb2layer.obj ogrdb2tablelayer.obj ogrdb2selectlayer.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

#EXTRAFLAGS = -I.. -I..\.. -I..\..\..\frmts\mem -DDEBUG_SQL -DDEBUG_DB2
EXTRAFLAGS = -I.. -I..\.. -I..\..\..\frmts\mem
default:	$(OBJ)

clean:
	-del *.obj *.pdb
