
OBJ	=	vrtdataset.obj vrtrasterband.obj vrtdriver.obj \
		vrtsources.obj vrtfilters.obj vrtsourcedrasterband.obj \
		vrtrawrasterband.obj vrtderivedrasterband.obj vrtwarped.obj

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS = 	-I..\raw

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

