
OBJ	=	vrtdataset.obj vrtrasterband.obj vrtdriver.obj \
		vrtsources.obj vrtfilters.obj vrtsourcedrasterband.obj \
		vrtrawrasterband.obj vrtderivedrasterband.obj vrtwarped.obj \
		vrtpansharpened.obj pixelfunctions.obj vrtmultidim.obj

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS = 	$(GEOS_CFLAGS)

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

