OBJ = clock.obj degrib1.obj degrib2.obj inventory.obj metaname.obj myerror.obj grib1tab.obj myutil.obj metaparse.obj weather.obj metaprint.obj grib2api.obj myassert.obj scan.obj tendian.obj hazard.obj

EXTRAFLAGS = -I ../g2clib $(SOFTWARNFLAGS)

GDAL_ROOT       =       ..\..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default: $(OBJ)
        xcopy /D /Y *.obj ..\..\..\o

clean:
	-del *.obj
