GDAL_ROOT	=	..\..
!INCLUDE $(GDAL_ROOT)\nmake.opt

OBJ	=	\
	pngdataset.obj


#EXTRAFLAGS = 	-I..\zlib -Ilibpng
!IFDEF PNG_EXTERNAL_LIB
EXTRAFLAGS = 	-I..\zlib -I$(PNGDIR)
!ELSE
EXTRAFLAGS = 	-I..\zlib -Ilibpng
!ENDIF

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o
!IFNDEF PNG_EXTERNAL_LIB
	cd libpng
	$(MAKE) /f makefile.vc
	cd ..
!ENDIF

clean:
	-del *.obj
	cd libpng
	$(MAKE) /f makefile.vc clean
	cd ..

