
OBJ	=	dodsdataset2.obj

GDAL_ROOT	=	..\..

EXTRAFLAGS = -I$(DODS_DIR) -I$(DODS_DIR)\include -I$(DODS_DIR)\include\gnu -I$(DODS_DIR)\include\xdr -I$(DODS_DIR)\include\pthreads /DWIN32 /DWIN32_LEAN_AND_MEAN -DFRMT_dods $(DODS_FLAGS) /GR

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

