
# nmake makefile for gdal
# should go as makefile.vc in frmts/pcraster

OBJ = pcrasterdataset.obj pcrastermisc.obj pcrasterutil.obj \
	pcrasterrasterband.obj

!IFNDEF PCRASTER_EXTERNAL_LIB
EXTRAFLAGS = 	-Ilibcsf -DUSE_IN_GDAL
!ENDIF

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj \
	..\o
!IFNDEF PCRASTER_EXTERNAL_LIB
	cd libcsf
	$(MAKE) /f makefile.vc
	cd ..
!ENDIF

clean:
	-del *.obj
	cd libcsf
	$(MAKE) /f makefile.vc clean
	cd ..

