.TH "ogr_utilities" 1 "28 Jun 2006" "GDAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ogr_utilities \- OGR Utility Programs
The following utilities are distributed as part of the OGR Simple Features toolkit:
.PP
.PD 0
.IP "\(bu" 2
\fBogrinfo\fP 
.IP "\(bu" 2
\fBogr2ogr\fP 
.IP "\(bu" 2
\fBogrtindex\fP 
.PP

