list(INSERT CMAKE_MODULE_PATH 0
    "${CMAKE_CURRENT_LIST_DIR}/packages"
    "${CMAKE_CURRENT_LIST_DIR}/thirdparty")

# Backported modules from cmake versions
if(CMAKE_VERSION VERSION_LESS 3.16)
    list(INSERT CMAKE_MODULE_PATH 0 "${CMAKE_CURRENT_LIST_DIR}/3.16")
endif()
if(CMAKE_VERSION VERSION_LESS 3.14)
    list(INSERT CMAKE_MODULE_PATH 0 "${CMAKE_CURRENT_LIST_DIR}/3.14")
endif()
if(CMAKE_VERSION VERSION_LESS 3.13)
    list(INSERT CMAKE_MODULE_PATH 0 "${CMAKE_CURRENT_LIST_DIR}/3.13")
endif()
if(CMAKE_VERSION VERSION_LESS 3.12)
    list(INSERT CMAKE_MODULE_PATH 0 "${CMAKE_CURRENT_LIST_DIR}/3.12")
endif()
