
OBJ	=	ogrpdsdriver.obj ogrpdsdatasource.obj ogrpdslayer.obj
EXTRAFLAGS =	-I.. -I..\.. -I$(GDAL_ROOT)/frmts/pds

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



