OBJ     =       ogrsdedatasource.obj ogrsdedriver.obj ogrsdelayer.obj
EXTRAFLAGS =	-I.. -I..\.. -I$(SDE_INC)

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb

ogr_SDE.dll:	$(OBJ)
	link /dll $(LDEBUG) /out:ogr_SDE.dll $(OBJ) \
		$(GDALLIB) $(SDE_LIB)