
OBJ	=	\
	gifdataset.obj biggifdataset.obj gifabstractdataset.obj

GDAL_ROOT	=	..\..

EXTRAFLAGS = 	-Igiflib

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o
	cd giflib
	$(MAKE) /f makefile.vc
	cd ..

clean:
	-del *.obj
	cd giflib
	$(MAKE) /f makefile.vc clean
	cd ..


