
OBJ	=	ogrpgeodriver.obj ogrpgeodatasource.obj ogrpgeolayer.obj \
		ogrpgeotablelayer.obj  ogrpgeoselectlayer.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS = -I.. -I..\.. -I..\openfilegdb

default:	$(OBJ)

clean:
	-del *.obj *.pdb
