
OBJ =	geometryreader.obj geometrywriter.obj ogrflatgeobufdataset.obj ogrflatgeobuflayer.obj ogrflatgeobufeditablelayer.obj packedrtree.obj
EXTRAFLAGS =	-I. -I.. -I..\.. -I..\generic

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb
