#
# Makefile building opencad library
# 

OBJ = \
	r2000.obj \
	io.obj 

GDAL_ROOT	=	..\..\..\..\..
EXTRAFLAGS =	-I. -I.. -I..\.. -I..\..\.. -I..\..\..\.. -DOCAD_EXTERN=""

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.lib
	-del *.obj *.pdb