
OBJ	=	httpdriver.obj gmlcoverage.obj wcsutils.obj wcsdataset.obj wcsdataset100.obj wcsdataset110.obj wcsdataset201.obj wcsrasterband.obj

EXTRAFLAGS = -DHAVE_CURL $(CURL_CFLAGS) $(CURL_INC) -I$(GDAL_ROOT)/gcore -I$(GDAL_ROOT)/ogr -I$(GDAL_ROOT)/ogr/ogrsf_frmts/gml

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt


default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj
	-del *.dll
