GDAL_ROOT = ..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

OBJ	= intergraphdataset.obj intergraphband.obj ingrtypes.obj jpeghelper.obj

EXTRAFLAGS = -D_USE_MATH_DEFINES -I..\gtiff\libtiff

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o
	cd ..
	
clean:
	-del *.obj
	cd ..
