OBJ     =       geoconcept.obj geoconcept_syscoord.obj \
		ogrgeoconceptdriver.obj \
		ogrgeoconceptdatasource.obj ogrgeoconceptlayer.obj
EXTRAFLAGS =	-I.. -I..\.. /DGCIO_DLLEXPORT -DUSE_CPL

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb
