
OBJ	=	ozidataset.obj

GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

!IFDEF ZLIB_EXTERNAL_LIB
EXTRAFLAGS = $(ZLIB_INC)
!ELSE
EXTRAFLAGS = -I..\zlib
!ENDIF

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj

