
OBJ	=	ogrgeopackagedriver.obj ogrgeopackagedatasource.obj \
        ogrgeopackagelayer.obj ogrgeopackagetablelayer.obj ogrgeopackageutility.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS = -I.. -I..\.. $(SQLITE_INC)

default:	$(OBJ)

clean:
	-del *.lib
	-del *.obj *.pdb
	-del *.exe

