name: Android CMake build

on:
    push:
        paths-ignore:
            - 'doc/**'
            - 'docker/**'
        branches-ignore:
            - 'backport**'
            - 'dependabot**'
    pull_request:
        paths-ignore:
            - 'doc/**'
            - 'docker/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  android_cmake_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache
        with:
          path: |
                ${{ github.workspace }}/ccache.tar.gz
          key: ${{ runner.os }}-cache-android-cmake-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cache-android-cmake-${{ github.ref_name }}-
            ${{ runner.os }}-cache-android-cmake-

      - name: Build
        run: docker run -e WORK_DIR="$PWD" -v $PWD:$PWD ubuntu:20.04 $PWD/.github/workflows/android_cmake/start.sh
