name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions:
  contents: read

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport

    permissions:
      pull-requests: write
