name: Conda

on:
    push:
        paths-ignore:
            - 'doc/**'
            - 'docker/**'
        branches-ignore:
            - 'backport**'
            - 'dependabot**'

    # Disabled because run is quite slow, especially for Mac
    #pull_request:
    #    paths-ignore:
    #        - 'doc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  build:
    name: Conda ${{ matrix.platform }}

    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        # macos-15-intel: Intel
        # macos-14: arm64
        platform: ['ubuntu-latest','windows-latest','macos-15-intel','macos-14','ubuntu-24.04-arm']

    env:
      GHA_CI_PLATFORM: ${{ matrix.platform }}
      CACHE_NUMBER: 0

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Support longpaths
      run: git config --system core.longpaths true
      if: matrix.platform == 'windows-latest'

    - name: Cache Conda Environment
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('ci/travis/conda/**') }}
        restore-keys: |
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-
          ${{ runner.os }}-conda-

    - uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
      with:
        miniforge-version: latest
        use-mamba: true
        channels: conda-forge
        auto-update-conda: true

    - name: Remove conflicting libraries
      shell: bash -l {0}
      if: matrix.platform == 'windows-latest'
      run: |
          rm -rf C:/Strawberry || /bin/true

    - name: Setup
      shell: bash -l {0}
      run: |
          source ./ci/travis/conda/setup.sh

    - name: Build
      shell: bash -l {0}
      run: |
          source ../ci/travis/conda/compile.sh
      working-directory: ./gdal-feedstock

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ matrix.platform }}-conda-package
        path: ./gdal-feedstock/packages/

    - name: Deploy to gdal-master Conda channel
      if: github.repository == 'OSGeo/GDAL' && github.ref == 'refs/heads/master'
      shell: bash -l {0}
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}   # zizmor: ignore[secrets-outside-env]
      run: |
          source ../ci/travis/conda/upload.sh
      working-directory: ./gdal-feedstock
