name: MacOS build

on:
    push:
        paths-ignore:
            - 'doc/**'
            - 'docker/**'
        branches-ignore:
            - 'backport**'
            - 'dependabot**'
    pull_request:
        paths-ignore:
            - 'doc/**'
            - 'docker/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:

  macos-conda:
    # Arm64
    runs-on: macos-14
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup ccache cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.ref_name }}-
            ${{ runner.os }}-ccache-

      - name: Cache Conda packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('ci/travis/osx/before_install.sh') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
            channels: conda-forge
            auto-update-conda: true
            use-mamba: true

      - name: Install Requirements
        shell: bash -l {0}
        run: |
          source ./ci/travis/osx/before_install.sh

      - name: Configure ccache
        shell: bash -l {0}
        run: |
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=1G" >> $GITHUB_ENV
          ccache -z

      - name: Build
        shell: bash -l {0}
        run: |
          source ./ci/travis/osx/install.sh

      - name: Show ccache stats
        shell: bash -l {0}
        run: ccache -sv

      - name: Run tests
        shell: bash -l {0}
        run: |
          source ./ci/travis/osx/script.sh
        env:
            # Emulate a few Travis-CI env variable so that some tests get properly skipped
            TRAVIS: true
            TRAVIS_OS_NAME: osx
            BUILD_NAME: macos_build_conda

  macos-homebrew:
    # M1 MacOS runner: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
    runs-on: macOS-15
    env:
      # Disable Arrow/Parquet because the VM provides libraries in /usr/local/lib/
      # that cause Illegal instruction error when running tests. I suspect the
      # Arrow/Parquet libraries to be built with AVX2 support but the VM worker
      # doesn't support it.
      # Disable use of libkml since boost headers cannot be found
      # Disable ODBC since the postinstall checks don't manage to find sql.h
      CMAKE_OPTIONS: -DCFITSIO_ROOT=/opt/homebrew/Cellar/cfitsio  -DPoppler_ROOT=/opt/homebrew/Cellar/poppler -DPROJ_ROOT=/opt/homebrew/Cellar/proj -DSPATIALITE_ROOT=/opt/homebrew/Cellar/libspatialite -DPostgreSQL_ROOT=/opt/homebrew/Cellar/libpq -DEXPAT_ROOT=/opt/homebrew/Cellar/expat -DXercesC_ROOT=/opt/homebrew/Cellar/xerces-c -DOpenSSL_ROOT=/opt/homebrew/Cellar/openssl -DPNG_ROOT=/opt/homebrew/Cellar/libpng -DJPEG_ROOT=/opt/homebrew/Cellar/jpeg-turbo -DEXPECTED_JPEG_LIB_VERSION=80 -DOpenJPEG_ROOT=/opt/homebrew/Cellar/openjpeg -DCURL_ROOT=/opt/homebrew/Cellar/curl -DGDAL_USE_LIBKML=OFF -DGDAL_USE_ODBC=OFF -DGDAL_ENABLE_MACOSX_FRAMEWORK=ON -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_CSHARP_BINDINGS=OFF -DBUILD_JAVA_BINDINGS=OFF
      CMAKE_UNITY_BUILD: OFF
      # CCACHE_DEBUG: 1
      cache-name: cmake-macos
    steps:
    - name: Setup xcode
      uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
      with:
        xcode-version: '26.3.0'
    - name: Checkout GDAL
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install dependencies
      run: |
        brew install --only-dependencies gdal 
        brew install boost ccache pkgconf swig
    - name: Restore cache
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      id: cache
      with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.base_ref }}${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ github.base_ref }}
            ${{ runner.os }}-${{ env.cache-name }}
    - name: Configure ccache
      run: |
          echo PATH=/opt/homebrew/opt/ccache/libexec:$PATH >> ${GITHUB_ENV}
          echo CCACHE_BASEDIR=$(pwd) >> ${GITHUB_ENV}
          echo CCACHE_DIR=$(pwd)/.ccache >> ${GITHUB_ENV}
          echo CCACHE_MAXSIZE=250M >> ${GITHUB_ENV}
          echo CCACHE_COMPILERCHECK=content >> ${GITHUB_ENV}
          echo CCACHE_DEBUGDIR=$(pwd)/.ccache-debug >> ${GITHUB_ENV}
          mkdir .ccache-debug
          ccache -z
      working-directory: ${{ github.workspace }}
    - name: Configure
      run: |
        cmake --version
        mkdir -p $GITHUB_WORKSPACE/build
        cmake -Werror=dev -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install-gdal ${CMAKE_OPTIONS} -DCMAKE_C_FLAGS=-Werror -DCMAKE_CXX_FLAGS=-Werror -DUSE_CCACHE=ON -DSQLite3_ROOT=$(brew --prefix sqlite) -DCMAKE_UNITY_BUILD=${CMAKE_UNITY_BUILD} -S "$GITHUB_WORKSPACE" -B "$GITHUB_WORKSPACE/build" -DWERROR_DEV_FLAG="-Werror=dev" 
    - name: Build
      run: |
        cmake --build $GITHUB_WORKSPACE/build -j 3
    - name: test (with ctest)
      run: |
        ctest --test-dir $GITHUB_WORKSPACE/build -V --output-on-failure -j 3 -R test-unit
      env:
        BUILD_NAME: "macos_build_brew"
    - name: Install
      run: cmake --build $GITHUB_WORKSPACE/build --target install -j 3
    - name: Test post-install usage (with macOSX Framework)
      run: |
         ./autotest/postinstall/test_framework.sh $GITHUB_WORKSPACE/install-gdal
    - name: ccache statistics
      if: always()
      run: ccache -s
    - name: Save cache
      if: always()
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.base_ref }}${{ github.ref_name }}-${{ github.run_id }}
    - name: Upload cache debug info
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: ccache-debug
        path: .ccache-debug
        include-hidden-files: true
