name: Perform Release

on:
  push:
    tags:
      - 'v*.*.*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

env:
  PROJ_VERSION: "9.7.1"

jobs:
  safety_checks:
    runs-on: ubuntu-latest
    outputs:
        RC: ${{ steps.unpack_tag.outputs.RC }}
        BETA: ${{ steps.unpack_tag.outputs.BETA }}
        VERSION: ${{ steps.unpack_tag.outputs.VERSION }}
        VERSION_WITH_RC: ${{ steps.unpack_tag.outputs.VERSION_WITH_RC }}
        COMPRESSED_VERSION: ${{ steps.unpack_tag.outputs.COMPRESSED_VERSION }}
        PRE_RELEASE: ${{ STEPS.unpack_tag.outputs.PRE_RELEASE }}
    steps:
      - name: ensure repo owner
        run: |
          if [[ ${{ github.repository_owner}} != 'OSGeo' ]]; then
            exit 1
          fi
      - name: extract tag info
        id: unpack_tag
        run: |
          export TAG=${{ github.ref_name }}
          export RC=$(python3 -c "print('' if 'rc' not in '$TAG'.lower() else ''.join('$TAG'.lower().rpartition('rc')[1:]).lower())")
          export BETA=$(python3 -c "print('' if 'beta' not in '$TAG'.lower() else ''.join('$TAG'.lower().rpartition('beta')[1:]).lower())")
          export VERSION=$(python3 -c "print('$TAG'.lower().lstrip('v').partition('rc')[0])")
          export VERSION_WITH_RC="${VERSION}${RC}"
          export COMPRESSED_VERSION=$(echo "$VERSION" | tr -d .)

          echo "RC=$RC" >> $GITHUB_OUTPUT
          echo "BETA=$BETA" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "COMPRESSED_VERSION=$COMPRESSED_VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_WITH_RC=$VERSION_WITH_RC" >> $GITHUB_OUTPUT

          if [ -z "$RC" ] && [ -z "$BETA" ]; then
            export PRE_RELEASE="false"
          else
            export PRE_RELEASE="true"
          fi
          echo "PRE_RELEASE=$PRE_RELEASE" >> $GITHUB_OUTPUT

  docker_builds:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [safety_checks]
    env:
      VERSION: ${{ needs.safety_checks.outputs.VERSION }}
      VERSION_WITH_RC: ${{ needs.safety_checks.outputs.VERSION_WITH_RC }}
    strategy:
      fail-fast: false
      matrix:
        platform: ["arm64", "amd64"]
        base: ["alpine-small", "alpine-normal", "ubuntu-small", "ubuntu-full"]
    name: ${{ matrix.base }}-${{ matrix.platform }}
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    permissions:
      attestations: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Docker
        uses: docker/setup-docker-action@3fb92d6d9c634363128c8cce4bc3b2826526370a # v4.4.0
        with:
          daemon-config: |
            {
              "debug": false,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract container metadata
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: |
            ghcr.io/osgeo/gdal
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
      - name: Build
        shell: bash -l {0}
        id: build
        env:
          BUILDKIT_PROGRESS: plain
        run: |
          cd docker/${{ matrix.base }}
          ./build.sh --platform linux/${{ matrix.platform }} --with-multi-arch --push --gdal ${{ github.ref_name }} --tag ${{ env.VERSION }} --release --proj ${{ env.PROJ_VERSION }}
          docker run --rm ghcr.io/osgeo/gdal:${{ matrix.base }}-${VERSION_WITH_RC}-${{ matrix.platform }} gdalinfo --formats
          docker run --rm ghcr.io/osgeo/gdal:${{ matrix.base }}-${VERSION_WITH_RC}-${{ matrix.platform }} ogrinfo --formats
  create-docker-manifest:
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    needs: [docker_builds, safety_checks]
    env:
      VERSION_WITH_RC: ${{ needs.safety_checks.outputs.VERSION_WITH_RC }}
    strategy:
      fail-fast: false
      matrix:
        tag: ["ubuntu-full", "ubuntu-small", "alpine-small", "alpine-normal"]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push multi-platform manifest
        run: |
          docker buildx imagetools create \
          -t ghcr.io/osgeo/gdal:${{ matrix.tag }}-${VERSION_WITH_RC} \
          ghcr.io/osgeo/gdal:${{ matrix.tag }}-${VERSION_WITH_RC}-amd64 \
          ghcr.io/osgeo/gdal:${{ matrix.tag }}-${VERSION_WITH_RC}-arm64
