name: Windows builds

on:
    push:
        paths-ignore:
            - 'doc/**'
            - 'docker/**'
        branches-ignore:
            - 'backport**'
            - 'dependabot**'
    pull_request:
        paths-ignore:
            - 'doc/**'
            - 'docker/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  windows_build:
    runs-on: windows-2022

    strategy:
      matrix:
        include:
          - VS_VERSION: Visual Studio 17
            VS_VER: 2022
            SDK: release-1930
            platform: x86
            PROJ_BRANCH: "9.3"
            LIBZSTD_URL: "https://github.com/facebook/zstd/releases/download/v1.4.5/zstd-v1.4.5-win32.zip"
            LIBDEFLATE_URL: "https://github.com/ebiggers/libdeflate/releases/download/v1.6/libdeflate-1.6-windows-i686-bin.zip"
            SWIG_URL: "https://raw.githubusercontent.com/rouault/downloads/refs/heads/main/swigwin-4.4.1.zip"

    env:
        VS_VERSION: ${{ matrix.VS_VERSION }}
        VS_VER: ${{ matrix.VS_VER }}
        SDK: ${{ matrix.SDK }}
        platform: ${{ matrix.platform }}
        PROJ_BRANCH: "${{ matrix.PROJ_BRANCH }}"
        LIBZSTD_URL: "${{ matrix.LIBZSTD_URL }}"
        LIBDEFLATE_URL: "${{ matrix.LIBDEFLATE_URL }}"
        SWIG_URL: "${{ matrix.SWIG_URL }}"
        APPVEYOR: true # to skip some tests
        PYTHON_VERSION: "3.10.5"
        CMAKE_POLICY_VERSION_MINIMUM: "3.5"  # cf https://cmake.org/cmake/help/latest/variable/CMAKE_POLICY_VERSION_MINIMUM.html

    steps:

      # To avoid git clone to mess with the line endings of GDAL autotest data
      # files that look like text, but should be handled as binary content
      - name: Set git core.autocrlf to false
        run: |
          git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set environment
        shell: pwsh
        run: |
            $env:PATH="C:\hostedtoolcache\windows\Python\$env:PYTHON_VERSION\$env:platform;C:\hostedtoolcache\windows\Python\$env:PYTHON_VERSION\$env:platform\Scripts;$env:PATH"
            if($env:platform -eq "x86")
            {
                $env:ARCHITECTURE="x86"
                $env:WIN64_ARG=""
                $env:CMAKE_ARCHITECTURE="Win32"
            }
            else
            {
                $env:ARCHITECTURE="amd64"
                $env:WIN64_ARG="WIN64=YES"
                $env:CMAKE_ARCHITECTURE="x64"
            }
            echo "PATH=$env:PATH" >> $env:GITHUB_ENV
            echo "ARCHITECTURE=$env:ARCHITECTURE" >> $env:GITHUB_ENV
            echo "WIN64_ARG=$env:WIN64_ARG" >> $env:GITHUB_ENV
            echo "CMAKE_ARCHITECTURE=$env:CMAKE_ARCHITECTURE" >> $env:GITHUB_ENV

      - name: Set compiler environment
        shell: cmd   # zizmor: ignore[misfeature]
        run: |
            if "%VS_VER%" == "2022" CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=%ARCHITECTURE%
            echo PATH=%PATH%>> %GITHUB_ENV%
            echo INCLUDE=%INCLUDE%>> %GITHUB_ENV%
            echo LIB=%LIB%>> %GITHUB_ENV%
            echo LIBPATH=%LIBPATH%>> %GITHUB_ENV%

      - name: Remove conflicting libraries
        shell: bash -l {0}
        run: |
            rm -rf C:/Strawberry || /bin/true

      - name: Detect AVX2
        shell: bash
        run: |
            set -e
            cl .github/workflows/detect-avx2.c
            if ./detect-avx2.exe; then
                    echo "AVX2 available on CPU"
                    echo "ARCH_FLAGS=/arch:AVX2" >> $GITHUB_ENV
            else
                    echo "AVX2 not available on CPU."
                    echo "ARCH_FLAGS=" >> $GITHUB_ENV
            fi

      - name: Build
        shell: pwsh
        run: |
            $ErrorActionPreference = 'continue'
            function exec
            {
                param ( [ScriptBlock] $ScriptBlock )
                & $ScriptBlock 2>&1 | ForEach-Object -Process { "$_" }
                if ($LastExitCode -ne 0) { exit $LastExitCode }
            }
            echo "ARCH_FLAGS = $env:ARCH_FLAGS"
            exec { git clone --depth=1 -b $env:PROJ_BRANCH https://github.com/OSGeo/PROJ proj }
            Import-PackageProvider NuGet -Force
            Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
            Install-Module Pscx -AllowClobber
            Install-Module VSSetup -Scope CurrentUser
            exec { pip install numpy }
            $env:SDK_ZIP="$env:SDK"+"-dev.zip"
            $env:SDK_URL="http://download.gisinternals.com/sdk/downloads/$env:SDK_ZIP"
            if(-Not (Test-Path -Path downloads)) { mkdir downloads }
            cd downloads
            if(-Not (Test-Path -Path $env:SDK_ZIP )) { Invoke-WebRequest "$env:SDK_URL" -OutFile "$env:SDK_ZIP" }
            $env:LIBZSTD_ZIP="libzstd.zip"
            if(-Not (Test-Path -Path $env:LIBZSTD_ZIP -PathType Leaf)) { Invoke-WebRequest "$env:LIBZSTD_URL" -OutFile "$env:LIBZSTD_ZIP" }
            $env:SWIG_ZIP="swigwin-4.4.1.zip"
            if(-Not (Test-Path -Path $env:SWIG_ZIP -PathType Leaf)) { Invoke-WebRequest "$env:SWIG_URL" -OutFile "$env:SWIG_ZIP" }
            # $env:LIBDEFLATE_ZIP="libdeflate.zip"
            # if(-Not (Test-Path -Path $env:LIBDEFLATE_ZIP -PathType Leaf)) { Invoke-WebRequest "$env:LIBDEFLATE_URL" -OutFile "$env:LIBDEFLATE_ZIP" }
            cd ..
            mkdir sdk
            cd sdk
            exec { 7z x ..\downloads\$env:SDK_ZIP }
            cd $env:SDK
            #exec { 7z x ..\..\downloads\$env:LIBZSTD_ZIP }
            exec { 7z x ..\..\downloads\$env:SWIG_ZIP }
            # exec { 7z x -y ..\..\downloads\$env:LIBDEFLATE_ZIP }
            cd ..
            $env:SDK_PREFIX="$env:GITHUB_WORKSPACE\sdk\$env:SDK"
            $env:SDK_LIB="$env:SDK_PREFIX\lib"
            cd $env:GITHUB_WORKSPACE
            cd proj
            mkdir build
            cd build
            $env:VCPKG_PLATFORM="$env:platform"+"-windows"
            exec { vcpkg install sqlite3:$env:VCPKG_PLATFORM }
            Invoke-WebRequest "https://sqlite.org/2018/sqlite-tools-win32-x86-3250100.zip" -OutFile "sqlite-tools-win32-x86-3250100.zip"
            7z x sqlite-tools-win32-x86-3250100.zip
            copy sqlite-tools-win32-x86-3250100/sqlite3.exe $env:GITHUB_WORKSPACE
            $env:PATH="$env:GITHUB_WORKSPACE;$env:PATH"
            $env:PROJ_INSTALL_DIR="$env:GITHUB_WORKSPACE"+"\install-proj"
            $env:CMAKE_INSTALL_PREFIX="-DCMAKE_INSTALL_PREFIX=" + $env:PROJ_INSTALL_DIR
            cmake -G $env:VS_VERSION -A $env:CMAKE_ARCHITECTURE .. $env:CMAKE_INSTALL_PREFIX -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBPROJ_SHARED=ON -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_SHARED_LIBS=ON -DENABLE_CURL=OFF -DENABLE_TIFF=OFF -DBUILD_PROJSYNC=OFF
            exec { cmake --build . --config Release --target install }
            #
            cd $env:GITHUB_WORKSPACE
            mkdir build
            cd build
            $env:SDK_BIN="$env:SDK_PREFIX\bin"
            $env:PATH="$env:SDK_BIN;$env:SDK\swigwin-4.4.1;$env:PATH"
            $env:GDAL_INSTALL_DIR="$env:GITHUB_WORKSPACE"+"\install-gdal"
            $env:CMAKE_INSTALL_PREFIX="-DCMAKE_INSTALL_PREFIX=" + $env:GDAL_INSTALL_DIR
            $env:PROJ_ROOT="-DPROJ_ROOT=" + $env:PROJ_INSTALL_DIR
            $env:CMAKE_PREFIX_PATH="-DCMAKE_PREFIX_PATH=" + $env:SDK_PREFIX
            $env:MYSQL_LIBRARY="-DMYSQL_LIBRARY=" + $env:SDK_LIB + "\libmysql.lib"
            $env:POPPLER_EXTRA_LIBRARIES="-DPOPPLER_EXTRA_LIBRARIES=" + $env:SDK_LIB + "\freetype.lib;" + $env:SDK_LIB + "\harfbuzz.lib"
            # We disable Spatialite and external geotiff as they link to gisinternals proj9 and we have the following linking error
            # referring to a file from the gisinternals build machine...
            # LINK : fatal error LNK1181: cannot open input file 'E:\buildsystem\release-1930\lib\proj9.lib' [D:\a\gdal\gdal\build\GDAL.vcxproj]
            # Disabling HDF4 (and netCDF) for similar reason: LINK : fatal error LNK1181: cannot open input file 'E:\buildsystem\release-1930\lib\mfhdf.lib'
            # Disabling KEA because of "keadataset.obj : error LNK2019: unresolved external symbol "public: static class H5::FileAccPropList const & const H5::FileAccPropList::DEFAULT"
            cmake -G $env:VS_VERSION -A $env:CMAKE_ARCHITECTURE .. $env:CMAKE_INSTALL_PREFIX -DCMAKE_BUILD_TYPE=Release $env:CMAKE_PREFIX_PATH -DCMAKE_C_FLAGS=" /WX $env:ARCH_FLAGS" -DCMAKE_CXX_FLAGS=" /WX $env:ARCH_FLAGS" -DGDAL_USE_DEFLATE=OFF $env:PROJ_ROOT $env:MYSQL_LIBRARY $env:POPPLER_EXTRA_LIBRARIES -DGDAL_USE_ZLIB_INTERNAL=ON -DECW_INTERFACE_COMPILE_DEFINITIONS="_MBCS;_UNICODE;UNICODE;_WINDOWS;LIBECWJ2;WIN32;_WINDLL;NO_X86_MMI" -DBUILD_CSHARP_BINDINGS=OFF -DBUILD_JAVA_BINDINGS=OFF -DOGR_ENABLE_DRIVER_LIBKML=OFF -DGDAL_USE_SPATIALITE=OFF -DGDAL_USE_GEOTIFF_INTERNAL=ON -DGDAL_USE_HDF4=OFF -DGDAL_USE_NETCDF=OFF -DGDAL_USE_WEBP=OFF -DGDAL_USE_KEA=OFF
            exec { cmake --build . --config Release --target install }

      - name: Run tests
        shell: pwsh
        run: |
            $ErrorActionPreference = 'continue'
            function exec
            {
                param ( [ScriptBlock] $ScriptBlock )
                & $ScriptBlock 2>&1 | ForEach-Object -Process { "$_" }
                if ($LastExitCode -ne 0) { exit $LastExitCode }
            }
            $env:SDK_PREFIX="$env:GITHUB_WORKSPACE\sdk\$env:SDK"
            $env:SDK_BIN="$env:SDK_PREFIX\bin"
            $env:PATH="$env:GITHUB_WORKSPACE\build\Release;$env:GITHUB_WORKSPACE\build\apps\Release;$env:GITHUB_WORKSPACE\install-proj\bin;$env:SDK_BIN;$env:PATH"
            $env:GDAL_DATA="$env:GITHUB_WORKSPACE\data"
            $env:DO_NOT_FAIL_ON_RECODE_ERRORS="YES"
            $env:MDB_ODBC_DRIVER_INSTALLED="YES"
            # The ca-bundle.crt file which we could point to is invalid in the current SDK
            # See https://github.com/gisinternals/buildsystem/issues/104
            $env:GDAL_HTTP_UNSAFESSL="YES"
            cd $env:GITHUB_WORKSPACE\autotest
            python3 -m pip install -Ur requirements.txt
            # For some reason I can't debug remotely, gdal.dll can'be loaded. Probably something missing in the path
            # exec { ctest --test-dir $env:GITHUB_WORKSPACE\build -C Release -V -j 3 -R autotest }

  build-windows-msys2-mingw:
    runs-on: windows-2022
    env:
      generator: MinGW Makefiles
      cache-name: cmake-mingw64
    defaults:
      run:
        shell: msys2 {0}
    steps:
      # To avoid git clone to mess with the line endings of GDAL autotest data
      # files that look like text, but should be handled as binary content
      - name: Set git core.autocrlf to false
        shell: bash -l {0}
        run: |
          git config --global core.autocrlf false
      - name: Checkout GDAL
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install development packages
        uses: msys2/setup-msys2@66cd2cce69caa17b53920067426061ca1de3a884 # v2.32.0
        with:
          msystem: MINGW64
          update: true
          # Disable mingw-w64-x86_64-crypto++ as it crashes at runtime on eedai_3 test. Likely a build issue with crypto++ itself
          install: |
            base-devel git mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-ccache
            mingw-w64-x86_64-pcre mingw-w64-x86_64-xerces-c mingw-w64-x86_64-zstd mingw-w64-x86_64-libarchive
            mingw-w64-x86_64-geos mingw-w64-x86_64-libspatialite mingw-w64-x86_64-proj
            mingw-w64-x86_64-cgal mingw-w64-x86_64-libfreexl mingw-w64-x86_64-hdf5 mingw-w64-x86_64-muparser mingw-w64-x86_64-netcdf mingw-w64-x86_64-poppler  mingw-w64-x86_64-podofo mingw-w64-x86_64-postgresql
            mingw-w64-x86_64-libgeotiff mingw-w64-x86_64-libpng mingw-w64-x86_64-libtiff mingw-w64-x86_64-openjpeg2
            mingw-w64-x86_64-python-pip mingw-w64-x86_64-python-numpy mingw-w64-x86_64-python-pytest mingw-w64-x86_64-python-setuptools mingw-w64-x86_64-swig mingw-w64-x86_64-python-psutil mingw-w64-x86_64-blosc mingw-w64-x86_64-libavif
      - name: Setup cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache
        with:
          path: ${{ github.workspace }}\.ccache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.base_ref }}${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ github.base_ref }}
            ${{ runner.os }}-${{ env.cache-name }}
      - name: Configure ccache
        run: |
          echo CCACHE_BASEDIR=$PWD >> ${GITHUB_ENV}
          echo CCACHE_DIR=$PWD/.ccache >> ${GITHUB_ENV}
          echo CCACHE_MAXSIZE=250M >> ${GITHUB_ENV}
          ccache -z
        working-directory: ${{ github.workspace }}
      - name: populate JAVA_HOME
        run: |
          echo "JAVA_HOME=$JAVA_HOME_11_X64" >> ${GITHUB_ENV}
      - name: Install python dependencies for autotest
        run: |
          # One of the dependencies of jsonschema 4.18 is rpds_py which requires a Rust compiler
          PYTHON_CMD=python3 && $PYTHON_CMD -m pip install "jsonschema<4.18"
          PYTHON_CMD=python3 && $PYTHON_CMD -m pip install pytest-sugar pytest-env pytest-benchmark filelock
      # Disable mySQL since C:/mysql/lib/mysqlclient.lib (unrelated to msys) is found, which causes linking issues
      # Set explicitly CMAKE_C|CXX_COMPILER otherwise C:/ProgramData/chocolatey/bin/gcc.exe would be used
      # Disable GDAL_ENABLE_DRIVER_HDF5 because of https://github.com/OSGeo/gdal/issues/11181
      - name: Configure
        run: |
          cmake -S . -B build -G "${generator}" -Werror=dev \
            -DCMAKE_BUILD_TYPE=release \
            -DCMAKE_C_FLAGS=-Werror \
            -DCMAKE_CXX_FLAGS=-Werror \
            -DWERROR_DEV_FLAG=-Werror=dev \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_PREFIX_PATH=/mingw64 \
            -DCMAKE_INSTALL_PREFIX=$PWD/install-gdal \
            "-DCMAKE_UNITY_BUILD=${CMAKE_UNITY_BUILD}" \
            -DGDAL_USE_MYSQL:BOOL=OFF \
            -DGDAL_ENABLE_DRIVER_HDF5=OFF
        working-directory: ${{ github.workspace }}
      - name: Build
        run: cmake --build build -j 3
        working-directory: ${{ github.workspace }}
      #- name: test
      #  run: cmake --build build --target quicktest
      #  working-directory: ${{ github.workspace }}
      #- name: test (with ctest)
      #  run: |
      #    ctest --test-dir $GITHUB_WORKSPACE/build -C Release -V -j 3
      #  env:
      #    BUILD_NAME: mingw64
      #    SKIP_OGR_GMLAS_HUGE_PROCESSING_TIME: YES
      #    SKIP_OGR_GMLAS_HTTP_RELATED: YES
      #    SKIP_TIFF_JPEG12: YES
      #    SKIP_VSIRAR: YES
      #  working-directory: ${{ github.workspace }}
      - name: Install
        run: cmake --build build --target install -j 3
        working-directory: ${{ github.workspace }}
      - name: Test post-install usage (with pkg-config)
        run: ./autotest/postinstall/test_pkg-config.sh $PWD/install-gdal
        working-directory: ${{ github.workspace }}
      - name: ccache statistics
        run: ccache -s

  build-windows-conda:
    runs-on: windows-2025-vs2026
    env:
        architecture: x64
        generator: Ninja
        cache-name: cmake-msvc
    steps:
    # To avoid git clone to mess with the line endings of GDAL autotest data
    # files that look like text, but should be handled as binary content
    - name: Set git core.autocrlf to false
      run: |
        git config --global core.autocrlf false
    - name: Checkout GDAL
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
    - name: populate JAVA_HOME
      shell: pwsh
      run: |
        echo "JAVA_HOME=$env:JAVA_HOME_11_X64" >> %GITHUB_ENV%
    - uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
      with:
        activate-environment: gdalenv
        miniforge-version: latest
        use-mamba: true
        auto-update-conda: true
        use-only-tar-bz2: false

    - name: Remove conflicting libraries
      shell: bash -l {0}
      run: |
          rm -rf C:/Strawberry || /bin/true
          rm -rf "C:/Program Files/OpenSSL/lib" || /bin/true
          rm -rf "C:/hostedtoolcache/windows/Python" || /bin/true
          # Below link.exe would otherwise be picked up by rust instead of MSVC one
          rm -f "C:/Program Files/Git/usr/bin/link.exe" || /bin/true

    - name: Install dependency
      shell: bash -l {0}
      run: |
        conda install --yes --quiet curl libiconv icu python=3.12 pip swig numpy "pytest!=9.1.0" pytest-env pytest-benchmark filelock zlib lxml jsonschema setuptools
        conda install --yes --quiet proj geos hdf4 hdf5 kealib highfive \
            libnetcdf openjpeg poppler libtiff libpng xerces-c expat libxml2 json-c \
            cfitsio freexl geotiff libjpeg-turbo libpq libspatialite libwebp-base pcre pcre2 postgresql \
            sqlite tiledb zstd cryptopp cgal "doxygen!=1.18.0" librttopo openssl liblzma-devel \
            openjdk ant qhull armadillo blas blas-devel libblas libcblas liblapack liblapacke blosc libarchive \
            libarrow pyarrow geoarrow-pyarrow libaec libheif libavif muparser cmake fsspec
        pip install -r doc/requirements.txt
    - name: Check CMake version
      shell: bash -l {0}
      run: |
        cmake --version
    - name: Install pdfium
      shell: bash -l {0}
      run: |
        curl -LOs https://github.com/rouault/pdfium_build_gdal_3_13/releases/download/pdfium_7724_v1/install-win10-vs2026-x64-rev7724.zip
        unzip install-win10-vs2026-x64-rev7724.zip
        mv install install-pdfium

    - name: Configure
      shell: bash -l {0}
      # Disable MySQL because of "error LNK2038: mismatch detected for '_MSC_VER': value '1800' doesn't match value '1900' in ogrmysqldatasource.obj" and other errors
      # Note that the leading space in CMAKE_C/CXX_FLAGS=" /WX" is due to using Bash on Windows that would
      # otherwise interpret /bla has a file relative to the Bash root directory and would replace it by a path like c:\Program Files\git\WX
      # BUILD_JAVA_BINDINGS=OFF because we get "Error occurred during initialization of VM.   Corrupted ZIP library: C:\Miniconda\envs\gdalenv\Library\bin\zip.dll" when running java. Not reproducible on a standard VM
      # Build PDF driver as plugin due to the PDFium build including libopenjp2 symbols which would conflict with external libopenjp2
      run: |
        mkdir -p $GITHUB_WORKSPACE/build
        cmake -G "${generator}" -Werror=dev "-DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install-gdal" "-DUSE_CCACHE=ON" "-DCMAKE_PREFIX_PATH=${CONDA}/envs/gdalenv" -DCMAKE_UNITY_BUILD=${CMAKE_UNITY_BUILD} -S "$GITHUB_WORKSPACE" -B "$GITHUB_WORKSPACE/build" -DGDAL_ENABLE_PLUGINS:BOOL=ON -DGDAL_ENABLE_PLUGINS_NO_DEPS:BOOL=ON -DGDAL_USE_PUBLICDECOMPWT:BOOL=ON -DPUBLICDECOMPWT_URL=https://github.com/rouault/PublicDecompWT -DBUILD_JAVA_BINDINGS=OFF -DBUILD_CSHARP_BINDINGS=ON -DGDAL_USE_MYSQL:BOOL=OFF -DCMAKE_C_FLAGS=" /WX" -DCMAKE_CXX_FLAGS=" /WX" -DWERROR_DEV_FLAG="-Werror=dev" -DCMAKE_BUILD_TYPE=Release -DPDFIUM_ROOT=$GITHUB_WORKSPACE/install-pdfium -DGDAL_ENABLE_DRIVER_PDF_PLUGIN:BOOL=ON -DCMAKE_UNITY_BUILD=ON -DOGR_ENABLE_DRIVER_TAB_PLUGIN=OFF -DOGR_ENABLE_DRIVER_GEOJSON_PLUGIN=OFF -DGDAL_USE_PCODEC=ON
    - name: Build
      shell: bash -l {0}
      run: cmake --build $GITHUB_WORKSPACE/build --config Release -j 2
      env:
        GIT_LFS_SKIP_SMUDGE: 1 # for PublicDecompWT github repository clone
    - name: Build HTML pages
      shell: bash -l {0}
      run: cmake --build $GITHUB_WORKSPACE/build --config Release -j 2 --target html
    - name: test
      shell: bash -l {0}
      run: |
        cmake --build $GITHUB_WORKSPACE/build --config Release --target quicktest
    - name: test (with ctest)
      shell: bash -l {0}
      run: |
        # Exclude doc spellcheck and example tests as they crash
        ctest --test-dir $GITHUB_WORKSPACE/build -C Release -V -j 3 -E doc
      env:
        SKIP_OGR_GMLAS_HUGE_PROCESSING_TIME: YES
        SKIP_OGR_GMLAS_HTTP_RELATED: YES
        SKIP_GDAL_HTTP_SSL_VERIFYSTATUS: YES
        BUILD_NAME: "build-windows-conda"
    - name: Install
      shell: bash -l {0}
      run: |
        cmake --build $GITHUB_WORKSPACE/build --config Release --target install
        export PATH=$GITHUB_WORKSPACE/install-gdal/bin:$GITHUB_WORKSPACE/install-gdal/local/bin:$PATH
        gdalinfo --version
        python -VV
        PYTHONPATH=$GITHUB_WORKSPACE/install-gdal/lib/site-packages python -c "from osgeo import gdal;print(gdal.VersionInfo(None))"
        export PATH=$GITHUB_WORKSPACE/install-gdal/Scripts:$PATH
        PYTHONPATH=$GITHUB_WORKSPACE/install-gdal/lib/site-packages gdal_edit --version
    - name: Check the build includes the expected drivers
      shell: bash -l {0}
      run: |
        export PATH=$GITHUB_WORKSPACE/install-gdal/local/bin:$GITHUB_WORKSPACE/install-gdal/bin:$PATH
        gdalinfo --formats > found_formats.txt
        ogrinfo --formats >> found_formats.txt
        cat found_formats.txt
        cat $GITHUB_WORKSPACE/.github/workflows/windows_conda_expected_gdalinfo_formats.txt $GITHUB_WORKSPACE/.github/workflows/windows_conda_expected_ogrinfo_formats.txt > expected_formats.txt
        dos2unix expected_formats.txt
        dos2unix found_formats.txt
        diff -u expected_formats.txt found_formats.txt
    - name: Show gdal.pc
      shell: bash -l {0}
      run: cat $GITHUB_WORKSPACE/build/gdal.pc
    - name: Test python setup.py install
      shell: bash -l {0}
      run: |
        cd $GITHUB_WORKSPACE/build/swig/python
        python setup.py install

  build-windows-minimum:
    runs-on: windows-2022
    env:
        architecture: x64
        generator: Visual Studio 17 2022
        GDAL_PYTHON_BINDINGS_WITHOUT_NUMPY: YES
    steps:
    # To avoid git clone to mess with the line endings of GDAL autotest data
    # files that look like text, but should be handled as binary content
    - name: Set git core.autocrlf to false
      run: |
        git config --global core.autocrlf false
    - name: Checkout GDAL
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
      with:
        activate-environment: gdalenv
        miniforge-version: latest
        use-mamba: true
        auto-update-conda: true
        use-only-tar-bz2: false
    - name: Install dependency
      shell: bash -l {0}
      run: |
        conda install --yes --quiet proj python=3.12 swig "pytest!=9.1.0" pytest-env pytest-benchmark filelock lxml cmake setuptools
    - name: Check CMake version
      shell: bash -l {0}
      run: |
        cmake --version

    - name: Remove conflicting libraries
      shell: bash -l {0}
      run: |
          rm -rf C:/Strawberry || /bin/true
          rm -rf "C:/Program Files/OpenSSL/lib" || /bin/true

    - name: Configure
      shell: bash -l {0}
      run: |
        mkdir -p $GITHUB_WORKSPACE/build
        cmake -A ${architecture} -G "${generator}" "-DCMAKE_PREFIX_PATH=${CONDA}/envs/gdalenv" -Werror=dev "-DCMAKE_CXX_COMPILER_LAUNCHER=clcache" -DCMAKE_UNITY_BUILD=${CMAKE_UNITY_BUILD} -S "$GITHUB_WORKSPACE" -B "$GITHUB_WORKSPACE/build" -DCMAKE_C_FLAGS=" /WX" -DCMAKE_CXX_FLAGS=" /WX" -DGDAL_USE_EXTERNAL_LIBS:BOOL=OFF -DWERROR_DEV_FLAG="-Werror=dev" -DCMAKE_CXX_STANDARD=20
    - name: Build
      shell: bash -l {0}
      run: cmake --build $GITHUB_WORKSPACE/build --config RelWithDebInfo -j 2
    - name: Configure with even less dependencies
      shell: bash -l {0}
      run: |
        rm -f build/CMakeCache.txt
        cmake -A ${architecture} -G "${generator}" "-DCMAKE_PREFIX_PATH=${CONDA}/envs/gdalenv" -Werror=dev "-DCMAKE_CXX_COMPILER_LAUNCHER=clcache" -DCMAKE_UNITY_BUILD=${CMAKE_UNITY_BUILD} -S "$GITHUB_WORKSPACE" -B "$GITHUB_WORKSPACE/build" -DCMAKE_C_FLAGS=" /WX" -DCMAKE_CXX_FLAGS=" /WX" -DGDAL_USE_EXTERNAL_LIBS:BOOL=OFF -DGDAL_USE_PNG_INTERNAL=OFF -DGDAL_USE_JPEG_INTERNAL=OFF -DGDAL_USE_JPEG12_INTERNAL=OFF -DGDAL_USE_GIF_INTERNAL=OFF -DGDAL_USE_LERC_INTERNAL=OFF -DGDAL_USE_LERCV1_INTERNAL=OFF -DGDAL_USE_QHULL_INTERNAL=OFF -DGDAL_USE_OPENCAD_INTERNAL=OFF -DWERROR_DEV_FLAG="-Werror=dev"
    - name: Configure with even less dependencies, disabling all optional drivers and algorithms
      shell: bash -l {0}
      run: |
        rm -f build/CMakeCache.txt
        cmake -A ${architecture} -G "${generator}" "-DCMAKE_PREFIX_PATH=${CONDA}/envs/gdalenv" -Werror=dev "-DCMAKE_CXX_COMPILER_LAUNCHER=clcache" -DCMAKE_UNITY_BUILD=${CMAKE_UNITY_BUILD} -S "$GITHUB_WORKSPACE" -B "$GITHUB_WORKSPACE/build" -DCMAKE_C_FLAGS=" /WX" -DCMAKE_CXX_FLAGS=" /WX" -DGDAL_USE_EXTERNAL_LIBS:BOOL=OFF -DGDAL_USE_PNG_INTERNAL=OFF -DGDAL_USE_JPEG_INTERNAL=OFF -DGDAL_USE_JPEG12_INTERNAL=OFF -DGDAL_USE_GIF_INTERNAL=OFF -DGDAL_USE_LERC_INTERNAL=OFF -DGDAL_USE_LERCV1_INTERNAL=OFF -DGDAL_USE_QHULL_INTERNAL=OFF -DGDAL_USE_OPENCAD_INTERNAL=OFF -DGDAL_BUILD_OPTIONAL_DRIVERS=OFF -DOGR_BUILD_OPTIONAL_DRIVERS=OFF -DGDAL_ENABLE_DRIVER_DERIVED=ON -DGDAL_VRT_ENABLE_RAWRASTERBAND=OFF -DGDAL_ENABLE_ALGORITHMS=OFF -DWERROR_DEV_FLAG="-Werror=dev"
    - name: Build
      shell: bash -l {0}
      run: cmake --build $GITHUB_WORKSPACE/build --config RelWithDebInfo -j 2

    - name: Re-enable shapefile driver and algorithms (otherwise lots of python tests would fail)
      shell: bash -l {0}
      run: |
        cmake -S "$GITHUB_WORKSPACE" -B "$GITHUB_WORKSPACE/build" -DOGR_ENABLE_DRIVER_SHAPE=ON -DOGR_ENABLE_DRIVER_SHAPE_PLUGIN=ON -DGDAL_ENABLE_ALGORITHMS=ON
    - name: Build
      shell: bash -l {0}
      run: cmake --build $GITHUB_WORKSPACE/build --config RelWithDebInfo -j 2

    # Works around https://github.com/actions/runner-images/issues/10055
    - name: Remove conflicting libraries
      shell: bash -l {0}
      run: |
          find "C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk" -name "msvcp140.dll" -exec rm {} \;

    - name: test (with ctest)
      shell: bash -l {0}
      run: |
        # gnm_test has suddenly started failing around June 16th 2024
        # Related to image windows-latest 20240603.1.0 / actions/runner-images#10004
        echo "def test_dummy(): pass" > $GITHUB_WORKSPACE/autotest/gnm/gnm_test.py
        ctest --test-dir $GITHUB_WORKSPACE/build -C RelWithDebInfo -V -j 3
      env:
        SKIP_GDAL_HTTP_SSL_VERIFYSTATUS: YES
        BUILD_NAME: "build-windows-minimum"
    - name: Show gdal.pc
      shell: bash -l {0}
      run: cat $GITHUB_WORKSPACE/build/gdal.pc

