/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GDAL {

using System;

public class ColorTable : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal ColorTable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(ColorTable obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  protected ColorTable() : this(IntPtr.Zero, false) {
  }

  ~ColorTable() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      gdalPINVOKE.delete_ColorTable(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public ColorTable(int arg0) : this(gdalPINVOKE.new_ColorTable(arg0), true) {
  }

  public ColorTable Clone() {
    IntPtr cPtr = gdalPINVOKE.ColorTable_Clone(swigCPtr);
    return (cPtr == IntPtr.Zero) ? null : new ColorTable(cPtr, false);
  }

  public int GetPaletteInterpretation() {
    return gdalPINVOKE.ColorTable_GetPaletteInterpretation(swigCPtr);
  }

  public int GetCount() {
    return gdalPINVOKE.ColorTable_GetCount(swigCPtr);
  }

  public SWIGTYPE_p_GDALColorEntry GetColorEntry(int arg0) {
    IntPtr cPtr = gdalPINVOKE.ColorTable_GetColorEntry(swigCPtr, arg0);
    return (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_GDALColorEntry(cPtr, false);
  }

  public int GetColorEntryAsRGB(int arg0, SWIGTYPE_p_GDALColorEntry arg1) {
    return gdalPINVOKE.ColorTable_GetColorEntryAsRGB(swigCPtr, arg0, SWIGTYPE_p_GDALColorEntry.getCPtr(arg1));
  }

  public void SetColorEntry(int arg0, SWIGTYPE_p_GDALColorEntry arg1) {
    gdalPINVOKE.ColorTable_SetColorEntry(swigCPtr, arg0, SWIGTYPE_p_GDALColorEntry.getCPtr(arg1));
  }

}

}
