/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GDAL {

using System;

public class GCP : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal GCP(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(GCP obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  protected GCP() : this(IntPtr.Zero, false) {
  }

  ~GCP() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      gdalPINVOKE.delete_GCP(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public double GCPX {
    set {
      gdalPINVOKE.set_GCP_GCPX(swigCPtr, value);
    } 
    get {
      return gdalPINVOKE.get_GCP_GCPX(swigCPtr);
    } 
  }

  public double GCPY {
    set {
      gdalPINVOKE.set_GCP_GCPY(swigCPtr, value);
    } 
    get {
      return gdalPINVOKE.get_GCP_GCPY(swigCPtr);
    } 
  }

  public double GCPZ {
    set {
      gdalPINVOKE.set_GCP_GCPZ(swigCPtr, value);
    } 
    get {
      return gdalPINVOKE.get_GCP_GCPZ(swigCPtr);
    } 
  }

  public double GCPPixel {
    set {
      gdalPINVOKE.set_GCP_GCPPixel(swigCPtr, value);
    } 
    get {
      return gdalPINVOKE.get_GCP_GCPPixel(swigCPtr);
    } 
  }

  public double GCPLine {
    set {
      gdalPINVOKE.set_GCP_GCPLine(swigCPtr, value);
    } 
    get {
      return gdalPINVOKE.get_GCP_GCPLine(swigCPtr);
    } 
  }

  public string Info {
    set {
      gdalPINVOKE.set_GCP_Info(swigCPtr, value);
    } 
    get {
      return gdalPINVOKE.get_GCP_Info(swigCPtr);
    } 
  }

  public string Id {
    set {
      gdalPINVOKE.set_GCP_Id(swigCPtr, value);
    } 
    get {
      return gdalPINVOKE.get_GCP_Id(swigCPtr);
    } 
  }

  public GCP(double x, double y, double z, double pixel, double line, string info, string id) : this(gdalPINVOKE.new_GCP(x, y, z, pixel, line, info, id), true) {
  }

}

}
