/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GDAL {

using System;

public class SWIGTYPE_p_double_6 {
  private IntPtr swigCPtr;

  internal SWIGTYPE_p_double_6(IntPtr cPtr, bool bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_double_6() {
    swigCPtr = IntPtr.Zero;
  }

  internal static IntPtr getCPtr(SWIGTYPE_p_double_6 obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }
}

}
