
OBJ	=	ogrxlsdriver.obj ogrxlsdatasource.obj ogrxlslayer.obj
EXTRAFLAGS =	-I.. -I..\.. $(FREEXL_CFLAGS)

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



