
OBJ	=	ogrpgdriver.obj ogrpgdatasource.obj ogrpglayer.obj \
		ogrpgtablelayer.obj ogrpgresultlayer.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS = -I.. -I..\.. -I$(PG_INC_DIR)

default:	$(OBJ)

clean:
	-del *.lib
	-del *.obj *.pdb
	-del *.exe
